/**********************************/
/**********GENEL DEGISKENLER*******/
/** ******************************* */
var TOKEN = document.getElementById('TOKEN').value;
var APPLICATIONROOT = document.getElementById('APPLICATIONROOT').value;
var LIMIT = 10;
var CUSTOMER_TREE_WIDTH = 320;
var TABLE_WIDTH = 900;
var TIMEOUT=120000;
var DEFAULT_HEADER_HEIGHT = '110';
var WESTPANELWIDTH = '263';

var EXPANDPANELWIDTH = '263'; 
var COLLAPSEPANELWIDTH = '35'; 

/** ******************************* */
/** ********GENEL SABITLER********* */
/** ******************************* */
var TEMEL_FATURA = "TEMELFATURA";
var TICARI_FATURA = "TICARIFATURA";
var YOLCUBERABER_FATURA = "YOLCUBERABERFATURA";
var TEMELIRSALIYE = "TEMELIRSALIYE";

var PKZARFBAZINDALISTELETEXT ;
var PKOKUNMAYANZARFNUMBER ;

Ext.apply(
		Ext.form.VTypes, 
		{
			vkn:  function(v) {return /[0-9]{10,10}$/i.test(v);},
			vknText: 'Vergi Numarası formatına uygun değil',
			vknMask: /[0-9]/i
		}
);
Ext.apply(
		Ext.form.VTypes, 
		{
			tckn:  function(v) {return /[0-9]{11,11}$/i.test(v);},
			tcknText: 'TC Kimlik Numarası formatına uygun değil',
			tcknMask: /[0-9]/i
		}
);
Ext.apply(
		Ext.form.VTypes, 
		{
			vknTckn:  function(v) {return /[0-9]{10,11}$/i.test(v);},
			vknTcknText: 'Formata uygun değil',
			vknTcknMask: /[0-9]/i
		}
);
var kurumTipListe = [
	['Özel', 1]
    ,['Kamu', 2]
];

var kurumTipStore = new Ext.data.SimpleStore({
    fields: ['deger', 'anahtar'],
    data : kurumTipListe,
    id : 1
});
var sehirListesi = [ 'Adana',
                     'Adıyaman',
                     'Afyon',
                     'Ağrı',
                     'Aksaray',
                     'Amasya',
                     'Ankara',
                     'Antalya',
                     'Ardahan',
                     'Artvin',
                     'Aydın',
                     'Balıkesir',
                     'Bartın',
                     'Batman',
                     'Bayburt',
                     'Bilecik',
                     'Bingöl',
                     'Bitlis',
                     'Bolu',
                     'Burdur',
                     'Bursa',
                     'Çanakkale',
                     'Çankırı',
                     'Çorum',
                     'Denizli',
                     'Diyarbakır',
                     'Düzce',
                     'Edirne',
                     'Elazığ',
                     'Erzincan',
                     'Erzurum',
                     'Eskişehir',
                     'Gaziantep',
                     'Giresun',
                     'Gümüşhane',
                     'Hakkari',
                     'Hatay',
                     'Iğdır',
                     'Isparta',
                     'İstanbul',
                     'İzmir',
                     'K.maraş',
                     'Karabük',
                     'Karaman',
                     'Kars',
                     'Kastamonu',
                     'Kayseri',
                     'Kırıkkale',
                     'Kırklareli',
                     'Kırşehir',
                     'Kilis',
                     'Kocaeli',
                     'Konya',
                     'Kütahya',
                     'Malatya',
                     'Manisa',
                     'Mardin',
                     'Mersin',
                     'Muğla',
                     'Muş',
                     'Nevşehir',
                     'Niğde',
                     'Ordu',
                     'Osmaniye',
                     'Rize',
                     'Sakarya',
                     'Samsun',
                     'Siirt',
                     'Sinop',
                     'Sivas',
                     'Ş.urfa',
                     'Şırnak',
                     'Tekirdağ',
                     'Tokat',
                     'Trabzon',
                     'Tunceli',
                     'Uşak',
                     'Van',
                     'Yalova',
                     'Yozgat',
                     'Zonguldak'					  
];

// tum ulkeleri icerecek sekilde guncellenecek.
var ulkeListesi = [  
'Abd Minor Outlying A'
,'Abd Virjin Adaları'
,'Afganistan'
,'Almanya'
,'Amerika Birleşik Dev'
,'Amerika Samoasi'
,'Andorra'
,'Angola'
,'Anguilla'
,'Antartika'
,'Antigua Ve Bermuda'
,'Arjantin'
,'Arnavutluk'
,'Aruba'
,'Avustralya'
,'Avustralya Okyanusu'
,'Avusturya'
,'Azerbeycan-Nahçivan'
,'Bahamalar'
,'Bahreyn'
,'Bangladeş'
,'Barbados'
,'Belçika'
,'Belize'
,'Benin'
,'Bermuda'
,'Beyaz Rusya'
,'Bhutan'
,'Bolivya'
,'Bosna-Hersek'
,'Bostvana'
,'Bouvet Adası'
,'Brezilya'
,'Brunei'
,'Bulgaristan'
,'Burkina Faso'
,'Burma'
,'Burundi'
,'Birleşik Arap Emirli'
,'Birleşik Devletler M'
,'Birleşik Krallik'
,'Bismark Archipelago'
,'Cape Verde'
,'Cayman Adaları'
,'Cebeli Tarik'
,'Ceuta Ve Melilla'
,'Cezayir'
,'Christmas Adaları'
,'Cook Adaları'
,'Cibuti'
,'Çad'
,'Çek Cumhuriyeti'
,'Çeçen Cumhuriyeti'
,'Çin Halk Cumhuriyeti'
,'Danimarka'
,'Dağistan Cumhuriyeti'
,'Dominik Cumhuriyeti'
,'Dominika'
,'Doğu Timor'
,'Dubai'
,'Ekvator'
,'Ekvator Ginesi'
,'El Salvador'
,'Endonezya'
,'Ermenistan'
,'Eritre'
,'Estonya'
,'Etiyopya'
,'Falkland Adaları'
,'Faroe Adaları'
,'Faroe Adaları'
,'Fas'
,'Fransa'
,'Fransiz Guyanasi'
,'Fransiz Güney Toprak'
,'Fransiz Polinezyasi'
,'Fiji'
,'Fildişi Sahili'
,'Filipinler'
,'Finlandiya'
,'Gabon'
,'Gambiya'
,'Gana'
,'Grenada'
,'Grönland'
,'Guadelup'
,'Guam'
,'Guatemala'
,'Guyana'
,'Güney Afrika Cumhuri'
,'Güney Fransiz Toprak'
,'Güney Georgia Ve Gün'
,'Güney Kore Cumhuriye'
,'Güney Yemen'
,'Gürcistan'
,'Gine'
,'Gine-Bissau'
,'Haiti'
,'Heard Adaları Ve Mc'
,'Hirvatistan'
,'Hollanda'
,'Hollanda Antilleri'
,'Honduras'
,'Hong Kong'
,'Hindistan'
,'Irak'
,'İngiliz Hint Oky.Top'
,'İngiliz Virgin Adala'
,'İran'
,'İrlanda'
,'İspanya'
,'İsrail'
,'İsveç'
,'İsviçre'
,'İtalya'
,'İzlanda'
,'İşgal Altindaki Fili'
,'Jamaika'
,'Japonya'
,'Kamboçya'
,'Kamerun'
,'Kanada'
,'Karadağ'
,'Katar'
,'Kazakistan'
,'Kenya'
,'Kibris Rum Kesimi'
,'Kirgizistan'
,'Kokos Adaları'
,'Kolombiya'
,'Komoro Adaları'
,'Kongo'
,'Kosova'
,'Kosta Rika'
,'Kutup Bölgeleri'
,'Kuveyt'
,'Kuzey Kibris Türk Cu'
,'Kuzey Kore Demokrati'
,'Kuzey Mariana Adalar'
,'Kuzey Yemen'
,'Kongo (Demokratik Cu)'
,'Küba'
,'Kiribati'
,'Laos'
,'Lesotho'
,'Letonya'
,'Lieshtenstein'
,'Lübnan'
,'Lüksemburg'
,'Liberya'
,'Libya'
,'Litvanya'
,'Macaristan'
,'Madagaskar'
,'Makao'
,'Makedonya'
,'Malavi'
,'Maldiv Adaları'
,'Malezya'
,'Malta'
,'Mali'
,'Marshall Adaları'
,'Martinik'
,'Mauritius'
,'Mayotte'
,'Meksika'
,'Melilla'
,'Misir'
,'Moldavya'
,'Monaco'
,'Montserrat'
,'Moritanya'
,'Mozambik'
,'Moğolistan'
,'Myanmar'
,'Mikronezya'
,'Namibya'
,'Nauru'
,'Nepal'
,'Norfolk Adası'
,'Norveç'
,'Nijer'
,'Nijerya'
,'Nikaragua'
,'Niue'
,'Orta Afrika Cumhuriy'
,'Özbekistan'
,'Pakistan'
,'Palau'
,'Panama'
,'Papua Yeni Gine'
,'Paraguay'
,'Peru'
,'Polonya'
,'Portekiz'
,'Pitcairn'
,'Reunion'
,'Romanya'
,'Ruanda'
,'Rusya Federasyonu'
,'San Marino'
,'Sao Tome And Princip'
,'Senegal'
,'Septe(Ceuta)'
,'Seyşel Adaları Ve Ba'
,'Sierra Leone'
,'Sirbistan'
,'Slovakya'
,'Slovenya'
,'Solomon Adaları'
,'Somali'
,'Sri Lanka'
,'St Vincent Ve Grenad'
,'St. Helena Ve Bağlan'
,'St. Kitts Ve Nevis'
,'St. Lucia'
,'St. Pierre Ve Miquel'
,'Sudan'
,'Surinam'
,'Suriye'
,'Suudi Arabistan'
,'Svaziland'
,'Samoa (Batı Samoa)'
,'Serbest Bölge (Ba-Bs)'
,'Singapur'
,'Şili'
,'Tacikistan'
,'Tayland'
,'Tayvan'
,'Togo'
,'Tokelau'
,'Tonga'
,'Trinidad Ve Tobago'
,'Tunus'
,'Turks Ve Caicos Adas'
,'Tuvalu'
,'Tanzanya (Birleşik C)'
,'Türkmenistan'
,'Türkiye'
,'Uganda'
,'Ukrayna'
,'Umman'
,'Uruguay'
,'Ürdün'
,'Vanuatu'
,'Vatikan'
,'Venezuella'
,'Vietnam'
,'Wallis Ve Futuna Ada'
,'Yakutistan'
,'Yemen'
,'Yeni Kalodenya Ve Ba'
,'Yeni Zelanda'
,'Yeni Zelanda Okyanus'
,'Yugoslavya(Eski Yugo)'
,'Yugoslavya(Sirbistan)'
,'Yunanistan'
,'Zambia'
,'Zimbabve'
];


var ulkeListesiKod = [
	['AF','Afghanistan'],
	['AX','Åland Islands'],
	['AL','Albania'],
	['DZ','Algeria'],
	['AS','American Samoa'],
	['AD','Andorra'],
	['AO','Angola'],
	['AI','Anguilla'],
	['AQ','Antarctica'],
	['AG','Antigua and Barbuda'],
	['AR','Argentina'],
	['AM','Armenia'],
	['AW','Aruba'],
	['AU','Australia'],
	['AT','Austria'],
	['AZ','Azerbaijan'],
	['BS','Bahamas'],
	['BH','Bahrain'],
	['BD','Bangladesh'],
	['BB','Barbados'],
	['BY','Belarus'],
	['BE','Belgium'],
	['BZ','Belize'],
	['BJ','Benin'],
	['BM','Bermuda'],
	['BT','Bhutan'],
	['BO','Bolivia (Plurinational State of)'],
	['BQ','Bonaire, Sint Eustatius and Saba'],
	['BA','Bosnia and Herzegovina'],
	['BW','Botswana'],
	['BV','Bouvet Island'],
	['BR','Brazil'],
	['IO','British Indian Ocean Territory'],
	['BN','Brunei Darussalam'],
	['BG','Bulgaria'],
	['BF','Burkina Faso'],
	['BI','Burundi'],
	['CV','Cabo Verde'],
	['KH','Cambodia'],
	['CM','Cameroon'],
	['CA','Canada'],
	['KY','Cayman Islands'],
	['CF','Central African Republic'],
	['TD','Chad'],
	['CL','Chile'],
	['CN','China'],
	['CX','Christmas Island'],
	['CC','Cocos (Keeling) Islands'],
	['CO','Colombia'],
	['KM','Comoros'],
	['CG','Congo'],
	['CD','Congo (Democratic Republic of the)'],
	['CK','Cook Islands'],
	['CR','Costa Rica'],
	['CI','Côte d\'Ivoire'],
	['HR','Croatia'],
	['CU','Cuba'],
	['CW','Curaçao'],
	['CY','Cyprus'],
	['CZ','Czechia'],
	['DK','Denmark'],
	['DJ','Djibouti'],
	['DM','Dominica'],
	['DO','Dominican Republic'],
	['EC','Ecuador'],
	['EG','Egypt'],
	['SV','El Salvador'],
	['GQ','Equatorial Guinea'],
	['ER','Eritrea'],
	['EE','Estonia'],
	['ET','Ethiopia'],
	['FK','Falkland Islands (Malvinas)'],
	['FO','Faroe Islands'],
	['FJ','Fiji'],
	['FI','Finland'],
	['FR','France'],
	['GF','French Guiana'],
	['PF','French Polynesia'],
	['TF','French Southern Territories'],
	['GA','Gabon'],
	['GM','Gambia'],
	['GE','Georgia'],
	['DE','Germany'],
	['GH','Ghana'],
	['GI','Gibraltar'],
	['GR','Greece'],
	['GL','Greenland'],
	['GD','Grenada'],
	['GP','Guadeloupe'],
	['GU','Guam'],
	['GT','Guatemala'],
	['GG','Guernsey'],
	['GN','Guinea'],
	['GW','Guinea-Bissau'],
	['GY','Guyana'],
	['HT','Haiti'],
	['HM','Heard Island and McDonald Islands'],
	['VA','Holy See'],
	['HN','Honduras'],
	['HK','Hong Kong'],
	['HU','Hungary'],
	['IS','Iceland'],
	['IN','India'],
	['ID','Indonesia'],
	['IR','Iran (Islamic Republic of)'],
	['IQ','Iraq'],
	['IE','Ireland'],
	['IM','Isle of Man'],
	['IL','Israel'],
	['IT','Italy'],
	['JM','Jamaica'],
	['JP','Japan'],
	['JE','Jersey'],
	['JO','Jordan'],
	['KZ','Kazakhstan'],
	['KE','Kenya'],
	['KI','Kiribati'],
	['KP','Korea (Democratic People\'s Republic of)'],
	['KR','Korea (Republic of)'],
	['KW','Kuwait'],
	['KG','Kyrgyzstan'],
	['LA','Lao People\'s Democratic Republic'],
	['LV','Latvia'],
	['LB','Lebanon'],
	['LS','Lesotho'],
	['LR','Liberia'],
	['LY','Libya'],
	['LI','Liechtenstein'],
	['LT','Lithuania'],
	['LU','Luxembourg'],
	['MO','Macao'],
	['MK','Macedonia (the former Yugoslav Republic of)'],
	['MG','Madagascar'],
	['MW','Malawi'],
	['MY','Malaysia'],
	['MV','Maldives'],
	['ML','Mali'],
	['MT','Malta'],
	['MH','Marshall Islands'],
	['MQ','Martinique'],
	['MR','Mauritania'],
	['MU','Mauritius'],
	['YT','Mayotte'],
	['MX','Mexico'],
	['FM','Micronesia (Federated States of)'],
	['MD','Moldova (Republic of)'],
	['MC','Monaco'],
	['MN','Mongolia'],
	['ME','Montenegro'],
	['MS','Montserrat'],
	['MA','Morocco'],
	['MZ','Mozambique'],
	['MM','Myanmar'],
	['NA','Namibia'],
	['NR','Nauru'],
	['NP','Nepal'],
	['NL','Netherlands'],
	['NC','New Caledonia'],
	['NZ','New Zealand'],
	['NI','Nicaragua'],
	['NE','Niger'],
	['NG','Nigeria'],
	['NU','Niue'],
	['NF','Norfolk Island'],
	['MP','Northern Mariana Islands'],
	['NO','Norway'],
	['OM','Oman'],
	['PK','Pakistan'],
	['PW','Palau'],
	['PS','Palestine, State of'],
	['PA','Panama'],
	['PG','Papua New Guinea'],
	['PY','Paraguay'],
	['PE','Peru'],
	['PH','Philippines'],
	['PN','Pitcairn'],
	['PL','Poland'],
	['PT','Portugal'],
	['PR','Puerto Rico'],
	['QA','Qatar'],
	['RE','Réunion'],
	['RO','Romania'],
	['RU','Russian Federation'],
	['RW','Rwanda'],
	['BL','Saint Barthélemy'],
	['SH','Saint Helena, Ascension and Tristan da Cunha'],
	['KN','Saint Kitts and Nevis'],
	['LC','Saint Lucia'],
	['MF','Saint Martin (French part)'],
	['PM','Saint Pierre and Miquelon'],
	['VC','Saint Vincent and the Grenadines'],
	['WS','Samoa'],
	['SM','San Marino'],
	['ST','Sao Tome and Principe'],
	['SA','Saudi Arabia'],
	['SN','Senegal'],
	['RS','Serbia'],
	['SC','Seychelles'],
	['SL','Sierra Leone'],
	['SG','Singapore'],
	['SX','Sint Maarten (Dutch part)'],
	['SK','Slovakia'],
	['SI','Slovenia'],
	['SB','Solomon Islands'],
	['SO','Somalia'],
	['ZA','South Africa'],
	['GS','South Georgia and the South Sandwich Islands'],
	['SS','South Sudan'],
	['ES','Spain'],
	['LK','Sri Lanka'],
	['SD','Sudan'],
	['SR','Suriname'],
	['SJ','Svalbard and Jan Mayen'],
	['SZ','Swaziland'],
	['SE','Sweden'],
	['CH','Switzerland'],
	['SY','Syrian Arab Republic'],
	['TW','Taiwan, Province of China[a]'],
	['TJ','Tajikistan'],
	['TZ','Tanzania, United Republic of'],
	['TH','Thailand'],
	['TL','Timor-Leste'],
	['TG','Togo'],
	['TK','Tokelau'],
	['TO','Tonga'],
	['TT','Trinidad and Tobago'],
	['TN','Tunisia'],
	['TR','Turkey'],
	['TM','Turkmenistan'],
	['TC','Turks and Caicos Islands'],
	['TV','Tuvalu'],
	['UG','Uganda'],
	['UA','Ukraine'],
	['AE','United Arab Emirates'],
	['GB','United Kingdom of Great Britain and Northern Ireland'],
	['US','United States of America'],
	['UM','United States Minor Outlying Islands'],
	['UY','Uruguay'],
	['UZ','Uzbekistan'],
	['VU','Vanuatu'],
	['VE','Venezuela (Bolivarian Republic of)'],
	['VN','Viet Nam'],
	['VG','Virgin Islands (British)'],
	['VI','Virgin Islands (U.S.)'],
	['WF','Wallis and Futuna'],
	['EH','Western Sahara'],
	['YE','Yemen'],
	['ZM','Zambia'],
	['ZW','Zimbabwe']
];




//vd listesi 12.03.2018 de güncellendi.
var vdListesi = [
'19 Mayıs',
'23 Temmuz',
'2 Eylül',
'30 Ağustos',
'5 Ocak',
'9 Eylül',
'Abana',
'Acıgöl',
'Acıpayam',
'Acısu',
'Adaklı',
'Adalar',
'Adana İhtisas',
'Adıyaman',
'Adilcevaz',
'Afşin',
'Ağaçören',
'Ağın',
'Ağlasun',
'Ağlı',
'Ağrı',
'Ahırlı',
'Ahlat',
'Ahmetli',
'Akçaabat',
'Akçadağ',
'Akçakale',
'Akçakent',
'Akçakoca',
'Akdağmadeni',
'Akdeniz',
'Akhisar',
'Akıncılar',
'Akkışla',
'Akkuş',
'Akören',
'Akpınar',
'Aksaray',
'Akseki',
'Aksu',
'Akşehir',
'Akyaka',
'Akyazı',
'Akyurt',
'Alaaddin',
'Alaca',
'Alacakaya',
'Alaçam',
'Aladağ',
'Alanya',
'Alaplı',
'Alaşehir',
'Alaybey',
'Alemdağ',
'Alemdar',
'Aliağa',
'Ali fuat cebesoy',
'Almus',
'Alpu',
'Altınekin',
'Altınova',
'Altınözü',
'Altıntaş',
'Altınyayla',
'Altunhisar',
'Alucra',
'Amasra',
'Amasya',
'Anadolu kurumlar',
'Anamur',
'Andırın',
'Ankara Kurumlar Vergi Dairesi Müdürlüğü',
'Antakya',
'Antalya İhtisas',
'Antalya kurumlar',
'Araban',
'Araç',
'Araklı',
'Aralık',
'Arapkir',
'Arda',
'Ardahan',
'Ardanuç',
'Ardeşen',
'Arguvan',
'Arhavi',
'Arıcak',
'Armutlu',
'Arpaçay',
'Arsin',
'Artova',
'Artvin',
'Asarcık',
'Asım gündüz',
'Aslanapa',
'Aslanbey',
'Aşkale',
'Atabey',
'Atışalanı',
'Atkaracalar',
'Avanos',
'Avcılar',
'Ayancık',
'Ayaş',
'Aybastı',
'Aydıncık',
'Aydıntepe',
'Ayrancı',
'Ayvacık',
'Ayvalık',
'Azdavay',
'Aziziye',
'Aziziye (ılıca)',
'Babadağ',
'Babaeski',
'Bafra',
'Bahçe',
'Bahçesaray',
'Bakırköy',
'Baklan',
'Bala',
'Balçova',
'Balışeyh',
'Balya',
'Banaz',
'Bandırma',
'Bartın',
'Baskil',
'Basmane',
'Başakşehir',
'Başçiftlik',
'Başkale',
'Başkent',
'Başmakçı',
'Başyayla',
'Batman',
'Battalgazi',
'Bayat',
'Bayburt',
'Bayındır',
'Baykan',
'Bayramiç',
'Bayramören',
'Bayrampaşa',
'Bekilli',
'Belen',
'Belkahve',
'Bergama',
'Besni',
'Beşikdüzü',
'Beşiktaş',
'Beşiri',
'Beyağaç',
'Beyazıt',
'Beydağ',
'Beydağı',
'Beykoz',
'Beylikdüzü',
'Beylikova',
'Beyoğlu',
'Beypazarı',
'Beyşehir',
'Beytüşşebab',
'Biga',
'Bigadiç',
'Bilecik',
'Bingöl',
'Birecik',
'Bismil',
'Bitlis',
'Bodrum',
'Boğaziçi kur.',
'Boğazkale',
'Boğazlıyan',
'Bolu',
'Bolvadin',
'Bor',
'Borçka',
'Bornova',
'Boyabat',
'Bozcaada',
'Bozdoğan',
'Bozkır',
'Bozkurt',
'Bozova',
'Boztepe',
'Bozüyük',
'Bozyazı',
'Bucak',
'Buharkent',
'Bulancak',
'Bulanık',
'Buldan',
'Burdur',
'Burhaniye',
'Bursa İhtisas',
'Bünyan',
'Büyükçekmece',
'Büyük mük. vd. md.',
'Büyükorhan',
'C.sıtkı tarancı',
'Ceyhan',
'Ceylanpınar',
'Cide',
'Cihanbeyli',
'Cizre',
'Cumayeri',
'Cumhuriyet',
'Çağlıyancerit',
'Çakabey',
'Çal',
'Çaldıran',
'Çamardı',
'Çamaş',
'Çameli',
'Çamlıca İhtisas',
'Çamlıdere',
'Çamlıhemşin',
'Çamlıyayla',
'Çamoluk',
'Çan',
'Çanakçı',
'Çanakkale',
'Çandır',
'Çankaya',
'Çankırı',
'Çapa',
'Çardak',
'Çarşamba',
'Çarşıbaşı',
'Çat',
'Çatak',
'Çatalca',
'Çatalpınar',
'Çatalzeytin',
'Çavdarhisar',
'Çavdır',
'Çay',
'Çaybaşı',
'Çaycuma',
'Çayeli',
'Çayıralan',
'Çayırlı',
'Çaykara',
'Çekerek',
'Çekirge',
'Çelebi',
'Çelikhan',
'Çeltik',
'Çeltikçi',
'Çemişgezek',
'Çerkeş',
'Çerkezköy',
'Çermik',
'Çeşme',
'Çıldır',
'Çınar',
'Çınarcık',
'Çiçekdağı',
'Çifteler',
'Çiftlik',
'Çiğli',
'Çilimli',
'Çine',
'Çinili',
'Çivril',
'Çobanlar',
'Çorlu',
'Çorlu İhtisas',
'Çorum',
'Çubuk',
'Çukurca',
'Çukurova',
'Çumra',
'Çüngüş',
'Daday',
'Dalaman',
'Damal',
'Darende',
'Dargeçit',
'Datça',
'Davraz',
'Davutpaşa',
'Dazkırı',
'Delice',
'Demirci',
'Demirköy',
'Demirözü',
'Demre',
'Denizli İhtisas',
'Derbent',
'Derebucak',
'Dereli',
'Derepazarı',
'Derik',
'Derince',
'Derinkuyu',
'Dernekpazarı',
'Develi',
'Devrek',
'Devrekani',
'Dışkapı',
'Dış tic.',
'Dicle',
'Didim',
'Digor',
'Dikili',
'Dikimevi',
'Dikmen',
'Dinar',
'Divriği',
'Diyadin',
'Dodurga',
'Doğanbey',
'Doğanhisar',
'Doğankent',
'Doğanşar',
'Doğanşehir',
'Doğanyol',
'Doğanyurt',
'Doğubeyazıt',
'Domaniç',
'Dörtdivan',
'Dörtyol',
'Dumlupınar',
'Durağan',
'Dursunbey',
'Düden',
'Düzce',
'Düziçi',
'Düzköy',
'Eceabat',
'Edremit',
'Efeler',
'Eflani',
'Ege',
'Eğil',
'Eğirdir',
'Ekinözü',
'Elbistan',
'Eldivan',
'Eleşkirt',
'Elmadağ',
'Elmalı',
'Emet',
'Emirdağ',
'Emirgazi',
'Enez',
'Erbaa',
'Erciş',
'Erciyes',
'Erdek',
'Erdemli',
'Ereğli',
'Erenköy',
'Erfelek',
'Ergani',
'Ermenek',
'Ertuğrulgazi',
'Eruh',
'Erzin',
'Esenler',
'Esenyurt',
'Eskil',
'Eskipazar',
'Eskişehir',
'Espiye',
'Eşme',
'Etimesgut',
'Evciler',
'Evren',
'Eynesil',
'Ezine',
'Fatih',
'Fatsa',
'Feke',
'Felahiye',
'Fethiye',
'Fevzipaşa',
'Fındıklı',
'Fırat',
'Finike',
'Foça',
'G. hacıköy',
'Galata',
'Gaziantep İhtisas',
'Gaziemir',
'Gazikent',
'Gaziler',
'Gaziosmanpaşa',
'Gazipaşa',
'Gebze İhtisas',
'Gediz',
'Gelendost',
'Gelibolu',
'Gemerek',
'Gemlik',
'Genç',
'Gercüş',
'Gerede',
'Gerger',
'Germencik',
'Gerze',
'Gevaş',
'Gevher nesibe',
'Geyve',
'Giresun',
'Göbeklitepe',
'Gökalp',
'Gökçeada',
'Gökçebey',
'Gökdere',
'Gökpınar',
'Göksun',
'Gölbaşı',
'Gölcük',
'Göle',
'Gölhisar',
'Gölköy',
'Gölmarmara',
'Gölova',
'Gölpazarı',
'Gölyaka',
'Gömeç',
'Gönen',
'Gördes',
'Görele',
'Göynücek',
'Göynük',
'Göztepe',
'Güce',
'Güçlükonak',
'Güdül',
'Gülağaç',
'Gülnar',
'Gülşehir',
'Gülyalı',
'Gümrükönü',
'Gümüşhane',
'Gümüşova',
'Gündoğmuş',
'Güneşli',
'Güney',
'Güneysınır',
'Güneysu',
'Güngören',
'Günyüzü',
'Gürgentepe',
'Güroymak',
'Gürpınar',
'Gürün',
'Güzelhisar',
'Güzelyurt',
'Hacıbektaş',
'Hacılar',
'Hadim',
'Hafik',
'Hakkari',
'Halfeti',
'Haliç İhtisas',
'Halkalı',
'Halkapınar',
'Hamamözü',
'Hamur',
'Han',
'Hanak',
'Hani',
'Hanönü',
'Harmancık',
'Harput',
'Harran',
'Hasanbeyli',
'Hasankeyf',
'Hasan tahsin',
'Hasköy',
'Hassa',
'Havran',
'Havsa',
'Havza',
'Haymana',
'Hayrabolu',
'Hayrat',
'Hazar',
'Hazro',
'Hekimhan',
'Hemşin',
'Hendek',
'Hınıs',
'Hızırbey',
'Hilvan',
'Hisar',
'Hisarcık',
'Hitit',
'Hizan',
'Hocalar',
'Hocapaşa',
'Honaz',
'Hopa',
'Horosan',
'Hozat',
'Hüyük',
'Iğdır',
'Ilgaz',
'Ilgın',
'Irmak',
'İbradı',
'İdil',
'İhsangazi',
'İhsaniye',
'İkitelli',
'İkizce',
'İkizdere',
'İliç',
'İlyasbey',
'İmamoğlu',
'İmranlı',
'İncesu',
'İncirliova',
'İnebolu',
'İnegöl İhtisas',
'İnegöl',
'İnhisar',
'İnönü',
'İpsala',
'İscehisar',
'İskilip',
'İslahiye',
'İspir',
'İstiklal',
'İvedik',
'İvrindi',
'İyidere',
'İzmir İhtisas',
'İznik',
'K.karabekir',
'Kabadüz',
'Kabataş',
'Kaçkar',
'Kadıköy',
'Kadınhan',
'Kadışehri',
'Kadifekale',
'Kadirli',
'Kağıthane',
'Kağızman',
'Kahta',
'Kale',
'Kalecik',
'Kalekapı',
'Kaleönü',
'Kaletepe',
'Kalkandere',
'Kaman',
'Kandıra',
'Kangal',
'Karaburun',
'Karabük',
'Karacabey',
'Karacasu',
'Karaçoban',
'Karadeniz',
'Karadeniz ereğli',
'Karaelmas',
'Karahallı',
'Karaisalı',
'Karakeçili',
'Karakoçan',
'Karakoyunlu',
'Karaman',
'Karamanlı',
'Karamürsel',
'Karapınar',
'Karapürçek',
'Karasu',
'Karataş',
'Karayazı',
'Karesi',
'Kargı',
'Karkamış',
'Karlıova',
'Karpuzlu',
'Kars',
'Karşıyaka',
'Kartal',
'Kasımpaşa',
'Kastamonu',
'Kaş',
'Kavak',
'Kavaklıdere',
'Kaymakkapı',
'Kaynarca',
'Kaynaşlı',
'Kayseri İhtisas',
'Kazan',
'Kazımkarabekir',
'Keban',
'Keçiborlu',
'Keçiören',
'Keles',
'Kelkit',
'Kemah',
'Kemaliye',
'Kemalpaşa',
'Kemer',
'Kemeraltı',
'Kepsut',
'Keskin',
'Keşan',
'Keşap',
'Kıbrıscık',
'Kığı',
'Kınık',
'Kırıkhan',
'Kırkağaç',
'Kırklareli',
'Kırkpınar',
'Kırşehir',
'Kızılbey',
'Kızılcahamam',
'Kızılırmak',
'Kızılmurat',
'Kızılören',
'Kızıltepe',
'Kilis',
'Kiraz',
'Kocaali',
'Kayseri İhtisas',
'Kocaeli İhtisas',
'Kocaköy',
'Kocamustafapaşa',
'Kocasinan',
'Kocatepe',
'Koçarlı',
'Kofcaz',
'Konak',
'Konya İhtisas',
'Kordon',
'Korgan',
'Korgun',
'Korkut',
'Korkuteli',
'Kovancılar',
'Koyulhisar',
'Kozaklı',
'Kozan',
'Kozanlı',
'Kozluk',
'Kozyatağı',
'Köprübaşı',
'Köprüköy',
'Körfez',
'Köse',
'Köşk',
'Köyceğiz',
'Kula',
'Kulp',
'Kulu',
'Kuluncak',
'Kumlu',
'Kumluca',
'Kumru',
'Kurşunlu',
'Kurtalan',
'Kurtdereli',
'Kurucaşile',
'Kuşadası',
'Kuyucak',
'Küçükçekmece',
'Küçükköy',
'Küçükyalı',
'Küre',
'Kürtün',
'Laçin',
'Ladik',
'Lalapaşa',
'Laleli',
'Lapseki',
'Lice',
'Liman',
'Lüleburgaz',
'M.karagüzel',
'Maçka',
'Maden',
'Mahmudiye',
'Malazgirt',
'Malkara',
'Maltepe',
'Manavgat',
'Manisa İhtisas',
'Manyas',
'Mardin',
'Marm. ereğlisi',
'Marmara',
'Marmara kur.',
'Marmaris',
'Maslak',
'Mazgirt',
'Mazıdağı',
'Mecidiyeköy',
'Mecitözü',
'Menderes',
'Menemen',
'Mengen',
'Meram',
'Mercan',
'Meriç',
'Mersin İhtisas',
'Merter',
'Merzifon',
'Mesir',
'Mesudiye',
'Mevlana',
'Mevlanakapı',
'Midyat',
'Mihalgazi',
'Mihalıççık',
'Milas',
'Mimarsinan',
'Mithatpaşa',
'Mucur',
'Mudanya',
'Mudurnu',
'Muğla',
'Muradiye',
'Muratlı',
'Muratpaşa',
'Murgul',
'Mustafakemalpaşa',
'Muş',
'Mut',
'Mutki',
'Nakil vasıta.',
'Nallıhan',
'Namık kemal',
'Narman',
'Nazilli',
'Nazimiye',
'Nevşehir',
'Niğde',
'Niksar',
'Nilüfer',
'Nizip',
'Nurdağı',
'Nurhak',
'Nuruosmaniye',
'Nusaybin',
'Of',
'Oğuzeli',
'Oğuzlar',
'Oltu',
'Olur',
'Orhaneli',
'Orhangazi',
'Orta',
'Ortaca',
'Ortaköy',
'Osmancık',
'Osmaneli',
'Osmangazi',
'Osmaniye',
'Ostim',
'Otlukbeli',
'Ovacık',
'Ödemiş',
'Ömerli',
'Özalp',
'Özvatan',
'Palu',
'Pamukkale',
'Pamukova',
'Pasinler',
'Patnos',
'Pazar',
'Pazarcık',
'Pazarlar',
'Pazaryeri',
'Pazaryolu',
'Pehlivanköy',
'Pendik',
'Perşembe',
'Pertek',
'Pervari',
'Pınarbaşı',
'Pınarhisar',
'Piraziz',
'Polatlı',
'Posof',
'Pozantı',
'Pötürge',
'Pülümür',
'Rami',
'Refahiye',
'Reşadiye',
'Reyhanlı',
'Rıhtım',
'Safranbolu',
'Sahil',
'Saimbeyli',
'Salıpazarı',
'Salihli adil ora',
'Samandağ',
'Samsat',
'Sandıklı',
'Sapanca',
'Saray',
'Saraydüzü',
'Saraykent',
'Sarayköy',
'Saraylar',
'Sarayönü',
'Sarıcakaya',
'Sarıgazi',
'Sarıgöl',
'Sarıkamış',
'Sarıkaya',
'Sarıoğlan',
'Sarıveliler',
'Sarıyahşi',
'Sarıyer',
'Sarız',
'Saruhanlı',
'Sason',
'Savaştepe',
'Savur',
'Seben',
'Seferihisar',
'Seğmenler',
'Selçuk',
'Selendi',
'Selim',
'Senirkent',
'Serik',
'Serinhisar',
'Setbaşı',
'Seydiler',
'Seydişehir',
'Seyhan',
'Seyitgazi',
'Sındırgı',
'Siirt',
'Silifke',
'Silivri',
'Silopi',
'Silvan',
'Simav',
'Sinanpaşa',
'Sincan',
'Sincik',
'Sinop',
'Site',
'Sivaslı',
'Siverek',
'Sivrice',
'Sivrihisar',
'Solhan',
'Soma',
'Sorgun',
'Söğüt',
'Söke',
'Suburcu',
'Sulakyurt',
'Sultanahmet',
'Sultanbeyli',
'Sultandağı',
'Sultanhisar',
'Suluova',
'Sulusaray',
'Sumbas',
'Sungurlu',
'Suruç',
'Susurluk',
'Susuz',
'Suşehri',
'Süleymaniye',
'Süleymannazif',
'Süleymanpaşa',
'Süloğlu',
'Sürmene',
'Sütçüler',
'Şabanözü',
'Şahinbey',
'Şalpazarı',
'Şaphane',
'Şarkışla',
'Şarkikaraağaç',
'Şarköy',
'Şavşat',
'Şebinkarahisar',
'Şefaatli',
'Şehitkamil',
'Şehitkerim',
'Şehitlik',
'Şemdinli',
'Şenkaya',
'Şenpazar',
'Şereflikoçhisar',
'Şırnak',
'Şile',
'Şiran',
'Şirinyer',
'Şirvan',
'Şişli',
'Şuhut',
'Şükrükanatlı',
'Taraklı',
'Taşbaşı',
'Taşıtlar',
'Taşkent',
'Taşköprü',
'Taşlıçay',
'Taşova',
'Tatvan',
'Tavas',
'Tavşanlı',
'Tefenni',
'Tekkeköy',
'Tekman',
'Tepecik',
'Tercan',
'Terme',
'Tınaztepe',
'Tire',
'Tirebolu',
'Tokat',
'Tomarza',
'Tonya',
'Topçumeydanı',
'Toprakkale',
'Torbalı',
'Toros',
'Tortum',
'Torul',
'Tosya',
'Tufanbeyli',
'Tuna',
'Tunceli',
'Turgutlu',
'Turhal',
'Tut',
'Tutak',
'Tuzla',
'Tuzluca',
'Tuzlukcu',
'Türkeli',
'Türkoğlu',
'Uğurludağ',
'Ula',
'Ulaş',
'Ulaştırma',
'Ulubey',
'Uluborlu',
'Uluçınar',
'Uludağ',
'Uludere',
'Ulukışla',
'Ulus',
'Uray',
'Urla',
'Uşak',
'Uzundere',
'Uzunköprü',
'Uzunmehmet',
'Üçkapılar',
'Ümraniye',
'Ünye',
'Ürgüp',
'Üsküdar',
'Üzümlü',
'Vakfıkebir',
'Van',
'Vatan İhtisas',
'Varto',
'Veraset ve harç',
'Vezirköprü',
'Viranşehir',
'Vize',
'Y.galip',
'Yağlıdere',
'Yahyalı',
'Yakacık',
'Yakakent',
'Yalıhüyük',
'Yalova',
'Yalvaç',
'Yamanlar',
'Yapraklı',
'Yatağan',
'Yavuzeli',
'Yayladağ',
'Yayladere',
'Yazıhan',
'Yedisu',
'Yeditepe',
'Yeğenbey',
'Yeni bosna',
'Yenice',
'Yeniçağa',
'Yenifakılı',
'Yenikapı',
'Yenimahalle',
'Yenipazar',
'Yenişarbademli m',
'Yenişehir',
'Yerköy',
'Yeşil',
'Yeşilçay',
'Yeşilhisar',
'Yeşilli',
'Yeşilova',
'Yeşilyurt',
'Yığılca',
'Yıldırım',
'Yıldırımbeyazıt',
'Yıldızeli',
'Yomra',
'Yozgat',
'Yumurtalık',
'Yunak',
'Yunusemre',
'Yusufeli',
'Yüksekova',
'Yüreğir',
'Zafer',
'Zara',
'Zeytinburnu',
'Zile',
'Zincirlikuyu',
'Ziyapaşa'];

var digerVergiKodlari = ["V0021","V0061","V0071","V0073","V0074","V0075","V0076","V0077","V1047","V1048","V4080",
                         "V4081","V9015","V9021","V9077","V8001","V8002","V4071","V8004","V8005","V8006","V8007",
                         "V8008","V0003","V0011","V9040","V4171","V9944","V0059"];


 var otvIstisnaMuafListesi = [
  	['101','101 - İhracat İstisnası'],
 	['102','102 - Diplomatik İstisna'],
 	['103','103 - Askeri Amaçlı İstisna'],
 	['104','104 - Petrol Arama Faaliyetlerinde Bulunanlara Yapılan Teslimler'],
 	['105','105 - Uluslararası Anlaşmadan Doğan İstisna'],
 	['106','106 - Diğer İstisnalar'],
 	['107','107 - 7/a Maddesi Kapsamında Yapılan Teslimler'],
 	['108','108 - Geçici 5. Madde Kapsamında Yapılan Teslimler']  
 ];

 var otvIstisnaMuafListesiDiger = [
   ['151','151 - ÖTV - İstisna olmayan diğer']
 ];

 
 var vergiIstisnaMuafListesi = [
   	['201','201 - 17/1 Kültür ve eğitim amacı taşıyan işlemler'],
	['202','202 - 17/2-a Sağlık, çevre ve sosyal yardım amaçlı işlemler'],
//  ['203','203 - Eğitim ve sosyal yardım amaçlı bedelsiz teslimler'],
	['204','204 - 17/2-c Yabancı diplomatik organ ve hayır kurumlarının bağışlarıyla ilgili mal ve hizmet alışları'],
	['205','205 - 17/2-d Taşınmaz kültür varlıklarına ilişkin teslimler ve mimarlık hizmetleri'],
	['206','206 - 17/2-e Mesleki kuruluşların işlemleri'],
	['207','207 - 17/3 Askeri fabrika'],
	['208','208 - 17/4-c Birleşme, devir, dönüşüm ve bölünme işlemleri'],
	['209','209 - 17/4-e Banka ve sigorta muameleleri vergisi kapsamına giren işlemler'],
//  ['210','210 - Kıymetli taş ve madenlerin, kıymetli kağıtların, hurda ve atık malların teslimi'],
	['211','211 - 17/4-h Zirai amaçlı veya köy tüzel kişiliklerince yapılan içme suyu teslimleri'],
	['212','212 - 17/4-ı Serbest bölgelerde verilen hizmetler'],
	['213','213 - 17/4-j Boru hattı ile yapılan petrol ve gaz taşımacılığı'],
	['214','214 - 17/4-k Sanayi bölgelerindeki arsa ve işyeri teslimleri ile konut yapı kooperatiflerinin üyelerine konut teslimleri'],
	['215','215 - 17/4-l Varlık yönetim şirketlerinin işlemleri'],
	['216','216 - 17/4-m Tasarruf mevduatı sigorta fonunun işlemleri'],
	['217','217 - 17/4-n Basın - Yayın ve Enformasyon Genel Müdürlüğüne verilen haber hizmetleri'],
	['218','218 - 17/4-o md. Gümrük Antrepoları, Geçici Depolama Yerleri ile Gümrüklü Sahalarda Vergisiz Satış Yapılan İşyeri, Depo ve Ardiye Gibi Bağımsız Birimlerin Kiralanması'],
	['219','219 - 17/4-p Hazine ve Arsa Ofisi Genel Müdürlüğünün işlemleri'],
	['220','220 - 17/4-r İki Tam Yıl Süreyle Sahip Olunan Taşınmaz ve İştirak Hisseleri ile 15/7/2023 tarihinden önce kurumların aktifinde kayıtlı Taşınmaz satışı'],
	['221','221 - Geçici 15 Konut yapı kooperatifleri, belediyeler ve sosyal güvenlik kuruluşlarına verilen inşaat taahhüt hizmeti'],
//  ['222','222 - Uluslararası anlaşmalar çerçevesinde Türkiye\'de yapılan toplantılarla ilgili teslim ve hizmetler'],
	['223','223 - Geçici 20/1 Teknoloji geliştirme bölgelerinde yapılan işlemler'],
//  ['224','224 - Karayolları ve Orman Genel Müdürlüklerinin taşınmaz teslimleri'],
	['225','225 - Geçici 23 Milli Eğitim Bakanlığına yapılan bilgisayar bağışları ile ilgili teslimler'],
	['226','226 - 17/2-b Özel Okulları, Üniversite ve Yüksekokullar Tarafından Verilen Bedelsiz Eğitim Ve Öğretim Hizmetleri'],
	['227','227 - 17/2-b Kanunların Gösterdiği Gerek Üzerine Bedelsiz Olarak Yapılan Teslim ve Hizmetler'],
	['228','228 - 17/2-b Kanunun (17/1) Maddesinde Sayılan Kurum ve Kuruluşlara Bedelsiz Olarak Yapılan Teslimler'],
	['229','229 - 17/2-b Gıda Bankacılığı Faaliyetinde Bulunan Dernek ve Vakıflara Bağışlanan Gıda, Temizlik, Giyecek ve Yakacak Maddeleri'],
	['230','230 - 17/4-g Külçe Altın, Külçe Gümüş Ve Kiymetli Taşlarin Teslimi'],
	['231','231 - 17/4-g Metal Plastik, Lastik, Kauçuk, Kağit, Cam Hurda Ve Atıkların Teslimi'],
	['232','232 - 17/4-g Döviz, Para, Damga Pulu, Değerli Kağıtlar, Hisse Senedi ve Tahvil Teslimleri'],
	['234','234 - 17/4-ş Konut Finansmanı Amacıyla Teminat Gösterilen ve İpotek Konulan Konutların Teslimi'],
	['235','235 - 16/1-c Transit ve Gümrük Antrepo Rejimleri İle Geçici Depolama ve Serbest Bölge Hükümlerinin Uygulandığiı Malların Teslimi'],
	['236','236 - 19/2 Usulüne Göre Yürürlüğe Girmiş Uluslararası Anlaşmalar Kapsamındaki İstisnalar (İade Hakkı Tanınmayan)'],
	['237','237 - 17/4-t 5300 Sayılı Kanuna Göre Düzenlenen Ürün Senetlerinin İhtisas/Ticaret Borsaları Aracılığıyla İlk Teslimlerinden Sonraki Teslim'],
	['238','238 - 17/4-u Varlıkların  Varlık  Kiralama  Şirketlerine  Devri  İle  Bu  Varlıkların  Varlık Kiralama Şirketlerince Kiralanması ve Devralınan Kuruma Devri'],
	['239','239 - 17/4-y Taşınmazların  Finansal  Kiralama  Şirketlerine  Devri, Finansal  Kiralama Şirketi Tarafından Devredene Kiralanması ve Devri'],
	['240','240 - 17/4-z Patentli Veya Faydalı Model Belgeli Buluşa İlişkin Gayri Maddi Hakların Kiralanması, Devri ve Satışı'],
	['241','241 - TürkAkım Gaz Boru Hattı Projesine İlişkin Anlaşmanın (9/b) Maddesinde Yer Alan Hizmetler'],
	['242','242 - 17/4-ö md. Gümrük Antrepoları, Geçici Depolama Yerleri ile Gümrüklü Sahalarda, İthalat ve İhracat İşlemlerine konu mallar ile transit rejim kapsamında işlem gören mallar için verilen ardiye, depolama ve terminal hizmetleri'],
	['250','250 - Kısmi İstisna Diğer'],
	
	['301','301 - 11/1-a Mal ihracatı'],
	['302','302 - 11/1-a Hizmet ihracatı'],
	['303','303 - 11/1-a Roaming hizmetleri'],
	['304','304 - 13/a Deniz, hava, demiryolu taşıma araç. tes. ile inşa, tadil, bakım, onarım'],
	['305','305 - 13/b Deniz, hava taşıma araç. için liman, hava mey. yapılan hiz.'],
	['306','306 - 13/c Petrol aramaları ve petrol boru haztlarının inşa ve modern. ilişkin teslim hiz.'],
	['307','307 - 13/c Maden Arama, Altın, Gümüş, ve Platin Madenleri İçin İşletme, Zenginleştirme Ve Rafinaj Faaliyetlerine İlişkin Teslim Ve Hizmetler KDVGUT-(II/8-4)'],
	['308','308 - 13/d Teşvikli yatırım mal tes.'],
	['309','309 - 13/e Limanlara bağlantı sağ. demiryolu hatları ile liman ve hava mey. inşa, yenilenme ve genişletilmesi'],
	['310','310 - 13/f Ulusal güvenlik amaçlı teslim ve hizmetler'],
	['311','311 - 14/1 Uluslararası taşımacılık'],
	['312','312 - 15/a Diplomatik organ ve misyonlara yapılan teslim ve hizmetler'],
	['313','313 - 15/b Uluslarası kuruluşlara yapılan teslim ve hizmetler'],
	['314','314 - 19/2 Usulüne göre yürürlüğe girmiş uluslararası anlaşmalar kapsamındaki istisnalar(İade hakkı tanınan)'],
	['315','315 - 14/3 İhraç konusu eşya taşıyan kamyon, çekici ve yarı romorklara yapılan motorin teslimleri'],
	['316','316 - 11/1-a Serbest böl. müş. fason hiz.'],
	['317','317 - 17/4-s Özürlülerin eğitim, meslek ve günlük yaşam. ilişkin araç-gereç ve bilgisayar programları'],
	['318','318 - Geçici 29 Yap-İşlet-Devret modeli projeler, kiralama karş. yapt. sağlık tesis.projeler, kiralama karş. yapt. eğitim öğretim tesis. tes. hiz.'],
	['319','319 - 13/g Başbakanlık Merkez Teşkilatına yapılan araç teslimler'],
	['320','320 - Geçici 16 İSMEP kapsamında İst. İl Özel İd. bağlı faal. göst. \"İst. Proje Koor. Brm.\"ne yapılacak tes. hiz.'],
	['321','321 - Geçici 26 BM, NATO(temsilcilikleri, bağlı program, fon, özel ihtisas), OECD resmi kullanımları için yapılacak mal tes. hiz. ifaları'],
	['322','322 - 11/1-a Türkiye\'de İkamet Etmeyenlere Özel Fatura ile Yapılan Teslimler (Bavul Ticareti)'],
	['323','323 - 13/ğ 5300 Sayılı Kanuna Göre Düzenlenen Ürün Senetlerinin İhtisas/Ticaret Borsaları Aracılığıyla İlk Teslimi'],
	['324','324 - 13/h Türkiye Kızılay Derneğine Yapılan Teslim ve Hizmetler ile Türkiye Kızılay Derneğinin Teslim ve Hizmetleri'],
	['325','325 - 13/ı Yem Teslimleri'],
	['326','326 - 13/ı Gıda, Tarım ve Hayvancılık Bakanlığı Tarafından Tescil Edilmiş Gübrelerin Teslimi'],
	['327','327 - 13/ı Gıda, Tarım ve Hayvancılık Bakanlığı Tarafından Tescil Edilmiş Gübrelerin İçeriğinde Bulunan Hammaddelerin Gübre Üreticilerine Teslimi'],
	['328','328 - 13/i Konut veya İşyeri Teslimleri'],
	['329','329 - Eğitimde Fırsatları Artırma ve Teknolojiyi İyileştirme Hareketi (FATİH)projesi Kapsamında Milli Eğitim Bakanlığına Yapılacak Mal Teslimi ve Hizmet İfası'],
	['330','330 - 13/j md. Organize Sanayi Bölgeleri ile Küçük Sanayi Sitelerinin İnşasına İlişkin Teslim ve Hizmetler'],
	['331','331 - 13/m  md.  Ar-Ge, Yenilik ve Tasarım Faaliyetlerinde Kullanılmak Üzere Yapılan Yeni Makina ve Teçhizat Teslimlerinde İstisna'],
	['332','332 - Geçici 39. Md.  İmalat Sanayiinde Kullanılmak Üzere Yapılan Yeni Makina ve Teçhizat Teslimlerinde İstisna'],
	['333','333 - 13/k md. Kapsamında Genel ve Özel Bütçeli Kamu İdarelerine, İl Özel İdarelerine, Belediyelere ve Köylere Bağışlanan Tesislerin İnşasına İlişkin İstisna'],
	['334','334 - 13/l md. Kapsamında Yabancılara Verilen Sağlık Hizmetlerinde İstisna'],
	['335','335 - 13/n md. Basılı Kitap ve Süreli Yayınların Teslimleri'],
	['336','336 - Geçici 40 UEFA Müsabakaları Kapsamında Yapılacak Teslim ve Hizmetler'],
  	['337','337 - Türk Akım Gaz Boru Hattı Projesine İlişkin Anlaşmanın (9/h) Maddesi Kapsamındaki Gaz Taşıma Hizmetleri'],
  	['338','338 - İmalatçıların Mal İhracatları'],
  	['339','339 - İmalat Sanayii ile Turizme Yönelik Yatırım Teşvik Belgesi Kapsamındaki İnşaat İşlerine İlişkin Teslim ve Hizmetler'],
	['340','340 - Elektrik Motorlu Taşıt Araçlarının Geliştirilmesine Yönelik Mühendislik Hizmetleri'],
	['341','341 - Afetzedelere Bağışlanacak Konutların İnşasına İlişkin İstisna'],
	['342','342 - Genel Bütçeli Kamu İdarelerine Bağışlanacak Taşınmazların İnşasına İlişkin İstisna'],
	['343','343 - Genel Bütçeli Kamu İdarelerine Bağışlanacak Konutların Yabancı Devlet Kurum ve Kuruluşlarına Teslimine İlişkin İstisna'],
	['350','350 - İstisna Diğer']
   	

]; 
 
 var vergiIstisnaListesi = [
		['301','301 - 11/1-a Mal ihracatı'],
	  	['338','338 - İmalatçıların Mal İhracatları']

 ];
 
 var vergiIstisnaMuafListesiDiger = [
		['351','351 - KDV - İstisna Olmayan Diğer']
	];
 
 var konaklamaVergisiIstisnaListesi = [
	 	['001','001- Diplomatik İstisna']
	 ];
 
 var konaklamaVergisiListesi = [
	  	['0','0%'],
	  	['2','2%']
	  ];
 
 //kdv oran combo-box gelistirmesi temmuz-2023
// 10 temmuz dahil degil.
 
 var kdvOranListesi  = [
		['1','1'],
		['8','8'],
		['10','10'],
		['18','18'],
		['20','20']
];
 
 var kdvOranListesi10TemmuzOncesi = [
	['1','1'],
	['8','8'],
	['18','18']
];
 
 var yeniKdvOranListesi = [
		['1','1'],
		['8','8'],
		['10','10'],
		['18','18'],
		['20','20']
	];
 
 //10-16 temmuz arası. 10-16 temmuz dahil.
 var kdvOranListesi1016TemmuzArasi  = [
		['1','1'],
		['8','8'],
		['10','10'],
		['18','18'],
		['20','20']
];
 
 //16temmuz sonrasi. 16 temmuz dahil degil.
 var kdvOranListesi16TemmuzSonrasi  = [
		['1','1'],
		['10','10'],
		['20','20']
];
 

 var kdvTevkifatKodOranListesi = {
			6013:	30,
			6014:	40,
			602:	90,
			6035:	50,
			6037:	70,
			604:	50,
			605:	50,
			606:	90,
			607:	90,
			608:	90,
			6095:	50,
			6097:	70,
			610:	90,
			611:	90,
			6127:	70,
			6129:	90,
			6137:	70,
			6139:	90,
			614:	50,
			6155:	50,
			6157:	70,
			616:	50,
			617:	70,
			618:	70,
			619:	70,
			620:	70,
			6175:	50,
			6185:	50,
			6195:	50,
			6205:	50,
			621:	90,
			622:	90,
			623:	50,
			624:	20,
			625:	30,
			626:	20,
			6274:	40,
			6275:	50,
			650:	0,
			801:	100,	
			802:	100,
			803:	100,
			804:	100,
			805:	100,
			806:	100,
			807:	100,
			808:	100,
			809:	100,
			810:	100,
			811:	100,
			812:	100,
			813:	100,
			814:	100,
			815:	100,
			816:	100,
			817:	100,
			818:	100,
			819:	100,
			820:	100,
			821:	100,
			822:	100,
			823:	100,
			824:	100,
			825:	100	
		}; 
 
 var kdvTevkifatKodAciklamaListesi = [
  	['6014','601 - Yapım İşleri ile Bu İşlerle Birlikte İfa Edilen Mühendislik-Mimarlık ve Etüt-Proje Hizmetleri [KDVGUT-(I/C-2.1.3.2.1)]'],
  	['602','602 - Etüt, plan-proje, danışmanlık, denetim vb'],
  	['6037','603 - Makine, teçhizat, demirbaş ve taşitlara ait tadil, bakım, onarım [KDVGUT- (I/C-2.1.3.2.3)]'],
  	['604','604 - Yemek servis hizmeti'],
  	['605','605 - Organizasyon hizmeti'],
  	['606','606 - İşgücü temin hizmetleri'],
  	['607','607 - Özel güvenlik hizmeti'],
  	['608','608 - Yapı denetim hizmetleri'],
  	['6097','609 - Fason olarak yaptirilan tekstil ve konfeksiyon işleri, çanta ve ayakkabı dikim işleri ve bu işlere aracılık hizmetleri [KDVGUT-(I/C-2.1.3.2.7)]'],
  	['610','610 - Turistik mağazalara verilen müşteri bulma/ götürme hizmetleri'],
  	['611','611 - Spor kulüplerinin yayın, reklam ve isim hakkı gelirlerine konu işlemleri'],
  	['6129','612 - Temizlik hizmeti [KDVGUT-(I/C-2.1.3.2.10)]'],
  	['6139','613 - Çevre ve bahçe bakım hizmetleri [KDVGUT-(I/C-2.1.3.2.11)]'],
  	['614','614 - Servis taşımacıliğı'],
  	['6157','615 - Her türlü baskı ve basim hizmetleri [KDVGUT-(I/C-2.1.3.2.12)]'],
  	['616','616 - Diğer hizmetler [KDVGUT-(I/C-2.1.3.2.13)]'],
  	['617','617 - Hurda metalden elde edilen külçe teslimleri'],
  	['618','618 - Hurda Metalden Elde Edilenler Dışındaki Bakır, Çinko, Demir Çelik, Alüminyum ve Kurşun Külçe Teslimi [KDVGUT-(I/C-2.1.3.3.1)]'],
  	['619','619 - Bakir, çinko ve alüminyum ürünlerinin teslimi'],
  	['620','620 - istisnadan vazgeçenlerin hurda ve atık teslimi'],
  	['621','621 - Metal, plastik, lastik, kauçuk, kâğit ve cam hurda ve atıklardan elde edilen hammadde teslimi'],
  	['622','622 - Pamuk, tiftik, yün ve yapaği ile ham post ve deri teslimleri'],
  	['623','623 - Ağaç ve orman ürünleri teslimi'],
  	['624','624 - Yük Taşımacılığı Hizmeti [KDVGUT-(I/C-2.1.3.2.11)]'],
  	['625','625 - Ticari Reklam Hizmetleri [KDVGUT-(I/C-2.1.3.2.15)]'],
  	['626','626 - Diğer Teslimler [KDVGUT-(I/C-2.1.3.3.7.)]'],
  	['6274','627 - (1/11/2022 tarihi öncesi) Demir-Çelik Ürünlerinin Teslimi [KDVGUT-(I/C-2.1.3.3.8)]'],
  	['6275','627 - Demir-Çelik Ürünlerinin Teslimi [KDVGUT-(I/C-2.1.3.3.8)]'],
  	['801','801 - Yapım İşleri ile Bu İşlerle Birlikte İfa Edilen Mühendislik-Mimarlık ve Etüt-Proje Hizmetleri[KDVGUT-(I/C-2.1.3.2.1)]'],
  	['802','802 - Etüt, Plan-Proje, Danışmanlık, Denetim ve Benzeri Hizmetler[KDVGUT-(I/C-2.1.3.2.2)]'],
  	['803','803 - Makine, Teçhizat, Demirbaş ve Taşıtlara Ait Tadil, Bakım ve Onarım Hizmetleri[KDVGUT- (I/C-2.1.3.2.3)]'],
  	['804','804 - Yemek Servis Hizmeti[KDVGUT-(I/C-2.1.3.2.4)]'],
  	['805','805 - Organizasyon Hizmeti[KDVGUT-(I/C-2.1.3.2.4)]'],
  	['806','806 - İşgücü Temin Hizmetleri[KDVGUT-(I/C-2.1.3.2.5)]'],
  	['807','807 - Özel Güvenlik Hizmeti[KDVGUT-(I/C-2.1.3.2.5)]'],
  	['808','808 - Yapı Denetim Hizmetleri[KDVGUT-(I/C-2.1.3.2.6)]'],
  	['809','809 - Fason Olarak Yaptırılan Tekstil ve Konfeksiyon İşleri, Çanta ve Ayakkabı Dikim İşleri ve Bu İşlere Aracılık Hizmetleri[KDVGUT-(I/C-2.1.3.2.7)]'],
  	['810','810 - Turistik Mağazalara Verilen Müşteri Bulma/ Götürme Hizmetleri[KDVGUT-(I/C-2.1.3.2.8)]'],
  	['811','811 - Spor Kulüplerinin Yayın, Reklâm ve İsim Hakkı Gelirlerine Konu İşlemleri[KDVGUT-(I/C-2.1.3.2.9)]'],
  	['812','812 - Temizlik Hizmeti[KDVGUT-(I/C-2.1.3.2.10)]'],
  	['813','813 - Çevre ve Bahçe Bakım Hizmetleri[KDVGUT-(I/C-2.1.3.2.10)]'],
  	['814','814 - Servis Taşımacılığı Hizmeti[KDVGUT-(I/C-2.1.3.2.11)]'],
  	['815','815 - Her Türlü Baskı ve Basım Hizmetleri[KDVGUT-(I/C-2.1.3.2.12)]'],
  	['816','816 - Hurda Metalden Elde Edilen Külçe Teslimleri[KDVGUT-(I/C-2.1.3.3.1)]'],
  	['817','817 - Hurda Metalden Elde Edilenler Dışındaki Bakır, Çinko, Demir Çelik, Alüminyum ve Kurşun Külçe Teslimi [KDVGUT-(I/C-2.1.3.3.1)]'],
  	['818','818 - Bakır, Çinko, Alüminyum ve Kurşun Ürünlerinin Teslimi[KDVGUT-(I/C-2.1.3.3.2)]'],
  	['819','819 - İstisnadan Vazgeçenlerin Hurda ve Atık Teslimi[KDVGUT-(I/C-2.1.3.3.3)]'],
  	['820','820 - Metal, Plastik, Lastik, Kauçuk, Kâğıt ve Cam Hurda ve Atıklardan Elde Edilen Hammadde Teslimi[KDVGUT-(I/C-2.1.3.3.4)]'],
  	['821','821 - Pamuk, Tiftik, Yün ve Yapağı İle Ham Post ve Deri Teslimleri[KDVGUT-(I/C-2.1.3.3.5)]'],
  	['822','822 - Ağaç ve Orman Ürünleri Teslimi[KDVGUT-(I/C-2.1.3.3.6)]'],
  	['823','823 - Yük Taşımacılığı Hizmeti [KDVGUT-(I/C-2.1.3.2.11)]'],
  	['824','824 - Ticari Reklam Hizmetleri [KDVGUT-(I/C-2.1.3.2.15)]'],
  	['825','825 - Demir-Çelik Ürünlerinin Teslimi [KDVGUT-(I/C-2.1.3.3.8)]']
//  	,
//  	['650','650 - Diğer']
  ];
 
 
 var ihracKayitliFaturaListesi = [
  	['701','701 - 3065 s. KDV Kanununun 11/1-c md. Kapsamındaki İhraç Kayıtlı Satış'],
  	['702','702 - DİİB ve Geçici Kabul Rejimi Kapsamındaki Satışlar'],
  	['703','703 - 4760 s. ÖTV Kanununun 8/2 Md. Kapsamındaki İhraç Kayıtlı Satış'],
  	['704','704 - 3065 sayılı KDV Kanununun (11/1-c) maddesi ve 4760 s. Ötv Kanununun 8/2. Md. Kapsamındaki İhraç Kayıtlı Satış']
  ];
 
 var ozelMatrahListesi = [
  	['801','801 - Milli Piyango, Spor Toto vb. Oyunlar'],
  	['802','802 - At yarışları ve diğer müşterek bahis ve talih oyunları'],
  	['803','803 - Profesyonel Sanatçıların Yer Aldığı Gösteriler, Konserler, Profesyonel Sporcuların Katıldığı Sportif Faaliyetler, Maçlar, Yarışlar ve Yarışmalar'],
  	['804','804 - Gümrük Depolarında ve Müzayede Mahallerinde Yapılan Satışlar'],
  	['805','805 - Altından Mamül veya Altın İçeren Ziynet Eşyaları İle Sikke Altınların Teslimi'],
  	['806','806 - Tütün Mamülleri'],
  	['807','807 – Muzır Neşriyat Kapsamındaki  Gazete, Dergi vb. Periyodik Yayınlar',],
  	['808','808 – Gümüşten Mamul veya Gümüş İçeren Ziynet Eşyaları ile Sikke Gümüşlerin Teslimi'],
  	['809','809 - Belediyeler taraf. yap. şehiriçi yolcu taşımacılığında kullanılan biletlerin ve kartların bayiler tarafından satışı'],
  	['810','810 – Ön Ödemeli Elektronik Haberleşme Hizmetleri'],
  	['811','811 - TŞOF Tarafından Araç Plakaları ile Sürücü Kurslarında Kullanılan Bir Kısım Evrakın Teslimi'],
  	['812','812 – KDV Uygulanmadan Alınan İkinci El Motorlu Kara Taşıtı veya Taşınmaz Teslimi']
  	]; 
 
 
 var fisTipListesi = [
	['AVANS', 'AVANS'],
	['YEMEK_FIS','YEMEK FİŞ TAHSİLATI'],
	['E-FATURA', 'E-FATURA'],
	['E-FATURA_IRSALIYE','İRSALİYE YERİNE GEÇEN E-FATURA'],
	['E-ARSIV','E-ARŞİV FATURA'],
	['E-ARSIV_IRSALIYE','İRSALİYE YERİNE GEÇEN E-FATURA E-ARŞİV FATURA'],
	['FATURA', 'FATURA'],
	['OTOPARK', 'OTOPARK'],
	['FATURA_TAHSILAT','FATURA TAHSILATI İŞLEMLERİ'],
	['FATURA_TAHSILAT_KOMISYONLU','KOMİSYONLU FATURA TAHSILATI İŞLEMLERİ']
];
 
 
 
	var ortam = document.getElementById('ORTAM').value;
	console.log(ortam);
	if(ortam != 'PROD')
	{
		var faturaTipiListesi = [
			['SATIŞ', 'SATIS'],
			['İADE', 'IADE'],
			['TEVKİFAT', 'TEVKIFAT'],
			['TEVKİFAT İADE', 'TEVKIFATIADE'],
			['İSTİSNA', 'ISTISNA'],
			['ÖZEL MATRAH', 'OZELMATRAH'],
			['İHRAÇ KAYITLI', 'IHRACKAYITLI'],
			['SGK', 'SGK'],
			['KONAKLAMA VERGİSİ','KONAKLAMAVERGISI']
		];
		
	} else {
		var faturaTipiListesi = [
			['SATIŞ', 'SATIS'],
			['İADE', 'IADE'],
			['TEVKİFAT', 'TEVKIFAT'],
			['TEVKİFAT İADE', 'TEVKIFATIADE'],
			['İSTİSNA', 'ISTISNA'],
			['ÖZEL MATRAH', 'OZELMATRAH'],
			['İHRAÇ KAYITLI', 'IHRACKAYITLI'],
			['SGK', 'SGK'],
			['KONAKLAMA VERGİSİ','KONAKLAMAVERGISI']
		];
			
	}

	
 var sgkFaturaTipList = [
			['ECZANE', 'SAGLIK_ECZ'],
			['HASTANE', 'SAGLIK_HAS'],
			['OPTİK', 'SAGLIK_OPT'],
			['MEDİKAL', 'SAGLIK_MED'],
			['ABONELİK', 'ABONELIK'],
			['MAL/HİZMET', 'MAL_HIZMET'],
			['DİĞER', 'DIGER'],
		];
		
 
 

	var halFaturaTipiListesi = [
		['SATIŞ', 'SATIS'],
		['KOMİSYONCU', 'KOMISYONCU']
	];
	
	var konaklamaFaturaListesi = [
		['SATIŞ', 'SATIS'],
		['VERGİ', 'KONAKVERGI']
	];
 
	var paraBirimleriListesi = [
		['Dirham','AED','AED'],
		['Afghani','AFN','AFN'],
		['Lek','ALL','ALL'],
		['Dram','AMD','AMD'],
		['Netherlands Antillian Guilder','ANG','ANG'],
		['Kwanza','AOA','AOA'],
		['Argentine Peso','ARS','ARS'],
		['Australian Dollar','AUD','AUD'],
		['Aruban Guilder','AWG','AWG'],
		['Azerbaijanian Manat','AZM','AZM'],
		['Convertible Mark','BAM','BAM'],
		['Barbados Dollar','BBD','BBD'],
		['Taka','BDT','BDT'],
		['Bulgarian Lev','BGN','BGN'],
		['Bahraini Dinar','BHD','BHD'],
		['Burundi Franc','BIF','BIF'],
		['Bermudian Dollar (customarily: Bermuda Dollar)','BMD','BMD'],
		['Brunei Dollar','BND','BND'],
		['Boliviano','BOB','BOB'],
		['Brazilian Real','BRL','BRL'],
		['Bahamian Dollar','BSD','BSD'],
		['Ngultrum','BTN','BTN'],
		['Pula','BWP','BWP'],
		['Belarussian Ruble','BYR','BYR'],
		['Belize Dollar','BZD','BZD'],
		['Canadian Dollar','CAD','CAD'],
		['Franc Congolais','CDF','CDF'],
		['Swiss Franc','CHF','CHF'],
		['Chilean Peso','CLP','CLP'],
		['Yuan Renminbi','CNY','CNY'],
		['Colombian Peso','COP','COP'],
		['Costa Rican Colon','CRC','CRC'],
		['Cuban Peso','CUP','CUP'],
		['Cape Verde Escudo','CVE','CVE'],
		['Cyprus Pound','CYP','CYP'],
		['Czech Koruna','CZK','CZK'],
		['Djibouti Franc','DJF','DJF'],
		['Danish Krone','DKK','DKK'],
		['Dominican Peso','DOP','DOP'],
		['Algerian Dinar','DZD','DZD'],
		['Kroon','EEK','EEK'],
		['Egyptian Pound','EGP','EGP'],
		['Nakfa','ERN','ERN'],
		['Ethopian Birr','ETB','ETB'],
		['Euro','EUR','€'],
		['Fiji Dollar','FJD','FJD'],
		['Falkland Islands Pound','FKP','FKP'],
		['Pound Sterling','GBP','GBP'],
		['Lari','GEL','GEL'],
		['Cedi','GHC','GHC'],
		['Gibraltar Pound','GIP','GIP'],
		['Dalasi','GMD','GMD'],
		['Guinea Franc','GNF','GNF'],
		['Quetzal','GTQ','GTQ'],
		['Guyana Dollar','GYD','GYD'],
		['Honk Kong Dollar','HKD','HKD'],
		['Lempira','HNL','HNL'],
		['Kuna','HRK','HRK'],
		['Gourde','HTG','HTG'],
		['Forint','HUF','HUF'],
		['Rupiah','IDR','IDR'],
		['New Israeli Sheqel','ILS','ILS'],
		['Indian Rupee','INR','INR'],
		['Iraqi Dinar','IQD','IQD'],
		['Iranian Rial','IRR','IRR'],
		['Iceland Krona','ISK','ISK'],
		['Jamaican Dollar','JMD','JMD'],
		['Jordanian Dinar','JOD','JOD'],
		['Yen','JPY','JPY'],
		['Kenyan Shilling','KES','KES'],
		['Som','KGS','KGS'],
		['Riel','KHR','KHR'],
		['Comoro Franc','KMF','KMF'],
		['North Korean Won','KPW','KPW'],
		['Won','KRW','KRW'],
		['Kuwaiti Dinar','KWD','KWD'],
		['Cayman Islands Dollar','KYD','KYD'],
		['Tenge','KZT','KZT'],
		['Kip','LAK','LAK'],
		['Lebanese Pound','LBP','LBP'],
		['Sri Lanka Rupee','LKR','LKR'],
		['Liberian Dollar','LRD','LRD'],
		['Loti','LSL','LSL'],
		['Lithuanian Litas','LTL','LTL'],
		['Latvian Lats','LVL','LVL'],
		['Libyan Dinar','LYD','LYD'],
		['Morrocan Dirham','MAD','MAD'],
		['Moldovan Leu','MDL','MDL'],
		['Malagasy Franc','MGF','MGF'],
		['Denar','MKD','MKD'],
		['Kyat','MMK','MMK'],
		['Tugrik','MNT','MNT'],
		['Pataca','MOP','MOP'],
		['Ouguiya','MRU','MRU'],
		['Maltese Lira','MTL','MTL'],
		['Mauritius Rupee','MUR','MUR'],
		['Rufiyaa','MVR','MVR'],
		['Kwacha','MWK','MWK'],
		['Mexican Peso','MXN','MXN'],
		['Malaysian Ringgit','MYR','MYR'],
		['Metical','MZM','MZM'],
		['Namibia Dollar','NAD','NAD'],
		['Naira','NGN','NGN'],
		['Cordoba Oro','NIO','NIO'],
		['Norwegian Krone','NOK','NOK'],
		['Nepalese Rupee','NPR','NPR'],
		['New Zealand Dollar','NZD','NZD'],
		['Rial Omani','OMR','OMR'],
		['Balboa','PAB','PAB'],
		['Nuevo Sol','PEN','PEN'],
		['Kina','PGK','PGK'],
		['Philippine Peso','PHP','PHP'],
		['Pakistan Rupee','PKR','PKR'],
		['Zloty','PLN','PLN'],
		['Guarani','PYG','PYG'],
		['Qatari Rial','QAR','QAR'],
		['Leu','ROL','ROL'],
		['Russian Ruble','RUB','RUB'],
		['Rwanda Franc','RWF','RWF'],
		['Saudi Riyal','SAR','SAR'],
		['Solomon Islands Dollar','SBD','SBD'],
		['Seychelles Rupee','SCR','SCR'],
		['Sudanese Dinar','SDD','SDD'],
		['Swedish Krona','SEK','SEK'],
		['Singapore Dollar','SGD','SGD'],
		['St. Helena Pound','SHP','SHP'],
		['Tolar','SIT','SIT'],
		['Slovak Koruna','SKK','SKK'],
		['Leone','SLL','SLL'],
		['Somali Shilling','SOS','SOS'],
		['Suriname Guilder','SRG','SRG'],
		['Dobra','STD','STD'],
		['El Salvador Colon','SVC','SVC'],
		['Syrian Pound','SYP','SYP'],
		['Lilangeni','SZL','SZL'],
		['Baht','THB','THB'],
		['Somoni','TJS','TJS'],
		['Manat','TMM','TMM'],
		['Tunisian Dinar','TND','TND'],
		['Pa&apos;anga','TOP','TOP'],
		['Türk Lirası','TRL','TL'],
		['Trinidad and Tobago Dollar','TTD','TTD'],
		['New Taiwan Dollar','TWD','TWD'],
		['Tanzanian Shilling','TZS','TZS'],
		['Hryvnia','UAH','UAH'],
		['Uganda Shilling','UGX','UGX'],
		['US Dollar','USD','$'],
		['Peso Uruguayo','UYU','UYU'],
		['Uzbekistan Sum','UZS','UZS'],
		['Bolivar','VEB','VEB'],
		['Dong','VND','VND'],
		['Vatu','VUV','VUV'],
		['Tala','WST','WST'],
		['CFA Franc','XAF','XAF'],
		['Silver','XAG','XAG'],
		['Gold','XAU','XAU'],
		['East Carribean Dollar','XCD','XCD'],
		['SDR','XDR','XDR'],
		['CFA Franc','XOF','XOF'],
		['Palladium','XPD','XPD'],
		['CFP Franc','XPF','XPF'],
		['Platinum','XPT','XPT'],
		['Yemeni Rial','YER','YER'],
		['New Dinar','YUM','YUM'],
		['Rand','ZAR','ZAR'],
		['Rumen Leyi','RON','RON'],
		['Kwacha','ZMK','ZMK'],
		['Zimbabwe Dollar','ZWD','ZWD']
	];
	
	
	var birimListesi = [
		['Gün',	'DAY'], ['Ay','MON'], ['Yıl','ANN'], ['Saat','HUR'], ['Dakika','D61'], ['Saniye','D62'], ['Adet','C62'],
		['Paket','PA'], ['Kutu','BX'], ['mg','MGM'], ['g','GRM'], ['kg','KGM'],['lt','LTR'], ['ton','TNE'],
		['Net Ton','NT'], ['Gross ton','GT'], ['mm','MMT'], ['cm','CMT'], ['m','MTR'], ['km','KTM'], ['ml','MLT'],
		['mm3','MMQ'], ['cm2','CMK'], ['cm3','CMQ'], ['dm2','DMK'], ['m2','MTK'], ['m3','MTQ'], ['kJ','KJO'], ['cl','CLT'], ['KWH','KWH'], ['MWH','MWH'],
		['Ton baş.taşıma kap.','CCT'], ['Brüt kalori','D30'], ['1000 lt','D40'], ['Saf alkol lt','LPA'],
		['kg.m2','B32'], ['Hücre adet','NCL'], ['Çift','PR'], ['1000 m3','R9'], ['Set','SET'], ['1000 adet','T3'],
		['SCM','Q37'], ['NCM','Q39'], ['mmBTU','J39'],['CM3','G52'],['Düzine','DZN'],['Metre Tül','LM'],['Asgari Maktu Vergi Tutarı (ÖTV)','AMVT'],['Has Ağırlık','HAGR'],['Karat','CT']
	];
	
	 var birimMap= {
			 'DAY':'Gün',
			 'MON':'Ay',
			 'ANN':'Yıl',
			 'HUR':'Saat',
			 'D61':'Dakika',
			 'D62':'Saniye',
			 'C62':'Adet',
			 'PA':'Paket',
			 'BX':'Kutu',
			 'MGM':'mg',
			 'GRM':'g',
			 'KGM':'kg',
			 'LTR':'lt',
			 'TNE':'ton',
			 'NT':'Net Ton',
			 'GT':'Gross ton',
			 'MMT':'mm',
			 'CMT':'cm',
			 'MTR':'m',
			 'KTM':'km',
			 'MLT':'ml',
			 'MMQ':'mm3',
			 'CMK':'cm2',
			 'CMQ':'cm3',
			 'MTK':'m2',
			 'MTQ':'m3',
			 'KJO':'kJ',
			 'CLT':'cl',
			 'KWH':'KWH',
			 'MWH':'MWH',
			 'CCT':'Ton baş.taşıma kap.',
			 'D30':'Brüt kalori',
			 'D40':'1000 lt',
			 'LPA':'Saf alkol lt',
			 'B32':'kg.m2',
			 'NCL':'Hücre adet',
			 'PR':'Çift',
			 'R9':'1000 m3',
			 'SET':'Set',
			 'T3':'1000 adet',
			 'LM':'Metre Tül',
			 'AMVT':'Asgari Maktu Vergi Tutarı (ÖTV)',
			 'HAGR':'Has Ağırlık',
			 'CT': 'Karat'
			  }
	 
	 var birimMapReverse= {
			 'Gün':'DAY',
			 'Ay':'MON',
			 'Yıl':'ANN',
			 'Saat':'HUR',
			 'Dakika':'D61',
			 'Saniye':'D62',
			 'Adet':'C62',
			 'Paket':'PA',
			 'Kutu':'BX',
			 'mg':'MGM',
			 'g':'GRM',
			 'kg':'KGM',
			 'lt':'LTR',
			 'ton':'TNE',
			 'Net Ton':'NT',
			 'Gross ton':'GT',
			 'mm':'MMT',
			 'cm':'CMT',
			 'm':'MTR',
			 'km':'KTM',
			 'ml':'MLT',
			 'mm3':'MMQ',
			 'cm2':'CMK',
			 'cm3':'CMQ',
			 'm2':'MTK',
			 'm3':'MTQ',
			 'kJ':'KJO',
			 'cl':'CLT',
			 'KWH':'KWH',
			 'MWH':'MWH',
			 'Ton baş.taşıma kap.':'CCT',
			 'Brüt kalori':'D30',
			 '1000 lt':'D40',
			 'Saf alkol lt':'LPA',
			 'kg.m2':'B32',
			 'Hücre adet':'NCL',
			 'Çift':'PR',
			 '1000 m3':'R9',
			 'Set':'SET',
			 '1000 adet': 'T3',
			 'Metre Tül':'LM',
			 'Asgari Maktu Vergi Tutarı (ÖTV)':'AMVT',
			 'Has Ağırlık':'HAGR',
			 'Karat': 'CT'
			  }
	
//	CFR,CIF,CIP,CPT,DAF,DDP,DDU,DEQ,DES,EXW,FAS,FCA,FOB,DAP,DAT
	var teslimSartiListesi = [
		['CFR',	'CFR'], ['CIF','CIF'], ['CIP','CIP'], ['CPT','CPT'], ['DAF','DAF'], ['DDP','DDP'], ['DDU','DDU'], ['DEQ','DEQ'], ['DES','DES']
		, ['EXW','EXW'], ['FAS','FAS'], ['FCA','FCA'], ['FOB','FOB'], ['DAP','DAP'], ['DPU','DPU']
	];
	
	
	var esyaKapCinsiListesi = [
['Çelik bidon','1A'],
['Alüminyum bidon','1B'],
['Kontraplak bidon','1D'],
['Esnek ambalaj kutu','1F'],
['Elyaflı silindir','1G'],
['Ahşap silindir','1W'],
['Ahşap varil','2C'],
['Beş galonluk çelik bidon','3A'],
['Beş galonluk plastik bidon','3H'],
['Torba, süper boy','43'],
['Çoklu torba','44'],
['Çelik kutu','4A'],
['Alüminyum kutu','4B'],
['Doğal ahşap kutu','4C'],
['Kontraplak kutu','4D'],
['Yeniden üretilmiş ahşap kutu','4F'],
['Elyaf tahta kutu','4G'],
['Plastik kutu','4H'],
['Plastik dokuma torba','5H'],
['Kumaş torba','5L'],
['Kağıt torba','5M'],
['Kompozit ambalaj, plastik kap','6H'],
['Kompozit ambalaj, cam kutu','6P'],
['Araba kabı','7A'],
['Ahşap kasa','7B'],
['Ahşap palet','8A'],
['Ahşap kasa','8B'],
['Ahşap paketi','8C'],
['Ortaboy sert plastik dolum konteynerı','AA'],
['Elyaf kap','AB'],
['Kağıt kap','AC'],
['Ahşap kap','AD'],
['Aerosol','AE'],
['Palet, modüler, yaka 80cms * 60cms','AF'],
['Sarılmış palet','AG'],
['Palet, 100 cms * 110 cms','AH'],
['Çift çeneli kepçe','AI'],
['Koni','AJ'],
['Top','AL'],
['Korumasız ampul','AM'],
['Korumalı ampül','AP'],
['Püskürteç','AT'],
['Kapsül','AV'],
['Kemer','B4'],
['Varil','BA'],
['Bobin','BB'],
['Şişe kasası/rafı','BC'],
['Tahta','BD'],
['Bohça','BE'],
['Balon, korunmasız','BF'],
['Torba','BG'],
['Demet','BH'],
['Çöp kutusu','BI'],
['Kova','BJ'],
['Sepet','BK'],
['Sıkıştırılmış balya','BL'],
['Kase','BM'],
['Sıkıştırılmamış balya','BN'],
['Şişe, korunmasız, silindirik','BO'],
['Balon, korunmasız','BP'],
['Şişe, korunmuş, silindirik','BQ'],
['Çubuk','BR'],
['Şişe, korunmasız, soğanbiçim','BS'],
['Sürgü','BT'],
['İzmarit','BU'],
['Şişe, korunmuş, soğanbiçim','BV'],
['Sıvılar için kutu','BW'],
['Kutu','BX'],
['Tahta, paket halinde/demet','BY'],
['Çıbuklar, paket halinde/demet','BZ'],
['Dikdörtgen teneke','CA'],
['Bira kasası','CB'],
['Yayık','CC'],
['Teneke ibrik','CD'],
['Balık sepeti','CE'],
['Sandık','CF'],
['Kafes','CG'],
['Sandık','CH'],
['Teneke kutu','CI'],
['Tabut','CJ'],
['Fıçı','CK'],
['Bobin','CL'],
['Kart','CM'],
['Konteyner','CN'],
['Damacana, korumasız','CO'],
['Damacana, korumalı','CP'],
['Kartuş','CQ'],
['Kasa','CR'],
['Kutu','CS'],
['Karton kutu','CT'],
['Fincan','CU'],
['Kapak','CV'],
['Rulo kafes','CW'],
['Silindirik teneke','CX'],
['Silindir','CY'],
['Tuval','CZ'],
['Kasa, çok tabakalı, plastik','DA'],
['Kasa, çok tabakalı, ahşap','DB'],
['Kasa, çok tabakalı, karton','DC'],
['Demir varil','DI'],
['Damacana','DJ'],
['Karton kasa','DK'],
['Plastik dökme kasa','DL'],
['Ahşap dökme kasa','DM'],
['Sebil/dağıtıcı','DN'],
['Damacana, korumalı','DP'],
['Bidon','DR'],
['Üst kapaksız plastik tepsi, tek tabaka','DS'],
['Üst kapaksız ahşap tepsi, tek tabaka','DT'],
['Üst kapaksız polistiren tepsi, tek tabaka','DU'],
['Üst kapaksız karton tepsi, tek tabaka','DV'],
['Üst kapaksız plastik tepsi, çift tabaka','DW'],
['Üst kapaksız karton tepsi, çift tabaka','DY'],
['Plastik torba','EC'],
['Kasa, palet tabanı ile','ED'],
['Ahşap kasa, palet tabanı ile','EE'],
['Karton kasa, palet tabanı ile','EF'],
['Plastik kasa, palet tabanı ile','EG'],
['Metal kasa, palet tabanı ile','EH'],
['İzotermik kasa','EI'],
['Zarf','EN'],
['Plastik esnek torba','FB'],
['Meyve kasası','FC'],
['Çerçeveli kasa','FD'],
['Plastik esnek depo','FE'],
['Küçük fıçı','FI'],
['Matara','FL'],
['Küçük sandık','FO'],
['Çerçeve','FR'],
['Streçlenmiş yemek kabı','FT'],
['Yanları üstü açık yük arabası','FW'],
['Esnek torba','FX'],
['Gaz şişesi','GB'],
['Kiriş','GI'],
['Konteyner, galon','GL'],
['Cam kap','GR'],
['Çul','GY'],
['Kiriş, demet/grup','GZ'],
['Saplı plastik sepet','HA'],
['Saplı ahşap sepet','HB'],
['Saplı karton sepet','HC'],
['Büyük fıçı','HG'],
['Askı','HN'],
['Kapaklı sepet','HR'],
['Ahşap sergi paketi','IA'],
['Karton sergi paketi','IB'],
['Plastik sergi paketi','IC'],
['Metal sergi paketi','ID'],
['Gösteri paketi','IE'],
['Şeffaf oluklu paket','IF'],
['Kağıt sarılı ambalaj','IG'],
['Plastik bidon','IH'],
['Şişe delikli karton paket','IK'],
['Tepsi, katı, kapaklı istiflenebilir','IL'],
['Külçe','IN'],
['Paket/grop halde külçe','IZ'],
['Jumbo boy torba','JB'],
['Beş galonluk dikdörtgen bidon','JC'],
['Sürahi','JG'],
['Kavanoz','JR'],
['Beş galonluk silindir bidon','JY'],
['Takım','KI'],
['Bagaj','LE'],
['Kütük','LG'],
['Pay','LT'],
['Kulp','LU'],
['Liftvan','LV'],
['Paket/grup kütükler','LZ'],
['Metal kasa','MA'],
['Çoklu çanta','MB'],
['Süt kasası','MC'],
['Metal konteyner','ME'],
['Metal kap','MR'],
['Çok duvarlı çuval','MS'],
['Mat','MT'],
['Plastik sarılmış kap','MW'],
['Kibrit kutusu','MX'],
['Ambalajsız','NE'],
['Ambalajsız, tek ünite','NF'],
['Ambalajsız, çok ünite','NG'],
['Yuva','NS'],
['Ağ','NT'],
['Plastik ağ tüp','NU'],
['Kumaş ağ tüp','NV'],
['Palet, CHEP 40x60 cm','OA'],
['Palet, CHEP 80x120 cm','OB'],
['Palet, CHEP 100x120 cm','OC'],
['Avustralya standart paleti','OD'],
['Palet,  110x100 cm','OE'],
['Nakliye platformu, belirtilmemiş ağırlık ve boyut','OF'],
['Blok','OK'],
['Sekiz kenar kutu','OT'],
['Dış konteyner','OU'],
['Tava','P2'],
['Küçük paket','PA'],
['Kombine açık uçlu kutu ve palet','PB'],
['Parsel','PC'],
['Palet, modüler 80 x 100 cm','PD'],
['Palet, modüler 80 x 120 cm','PE'],
['Kalem','PF'],
['Plaka','PG'],
['Sürahi','PH'],
['Boru','PI'],
['Meyve sepeti','PJ'],
['Paket','PK'],
['Gerdel','PL'],
['Kalas','PN'],
['Destek','PO'],
['Parça','PP'],
['Plastik kap','PR'],
['Demlik','PT'],
['Tepsi','PU'],
['Paket/grup boru','PV'],
['Palet','PX'],
['Paket/grup tabak','PY'],
['Paket/grup kalas','PZ'],
['Üstü açılmaz çelik bidon','QA'],
['Üstü açılır çelik bidon','QB'],
['Üstü açılmaz alüminyum bidon','QC'],
['Üstü açılır alüminyum bidon','QD'],
['Üstü açılmaz plastik bidon','QF'],
['Üstü açılır plastik bidon','QG'],
['Ahşap tıkaçlı varil','QH'],
['Üstü açılır ahşap varil','QJ'],
['Üstü açılmaz beş galonluk çelik bidon','QK'],
['Üstü açılır beş galonluk çelik bidon','QL'],
['Üstü açılmaz beş galonluk plastik bidon','QM'],
['Üstü açılır beş galonluk plastik bidon','QN'],
['Doğal ahşap kutu','QP'],
['Emniyet duvarlı doğal ahşap kutu','QQ'],
['Genişletilmiş plastik kutu','QR'],
['Yekpare plastik kutu','QS'],
['Çubuk','RD'],
['Halka','RG'],
['Raf, elbise askısı','RJ'],
['Raf','RK'],
['Makara','RL'],
['Rulo','RO'],
['Paket/grup çubuk','RZ'],
['Çuval','SA'],
['Levha','SB'],
['Sığ kasa','SC'],
['İğ','SD'],
['Deniz sandığı','SE'],
['Kesecik','SH'],
['Kızak','SI'],
['İskelet kasa','SK'],
['Taşıma paleti','SL'],
['Sac','SM'],
['Tel/kablo/iplik makarası','SO'],
['Plastik levha','SP'],
['Çelik kasa','SS'],
['Yaprak','ST'],
['Bavul','SU'],
['Çelik zarf','SV'],
['Vakumlu ambalaj','SW'],
['Set','SX'],
['Kılıf','SY'],
['Paket/grup yaprak','SZ'],
['Tablet','T1'],
['Küvet','TB'],
['Çay sandığı','TC'],
['Sıkılabilir tüp','TD'],
['Lastik','TE'],
['Genel tank konteynerı','TG'],
['Dikdörtgen tank','TK'],
['Teneke','TN'],
['Şarap fıçısı','TO'],
['Gövde','TR'],
['Bağ','TS'],
['Tüp','TU'],
['Enjektörlü tüp','TV'],
['Silindirik tank','TY'],
['Paket/grup tüpler','TZ'],
['Birim','UN'],
['Dökme gaz','VG'],
['Küçük şişe','VI'],
['Dökme sıvı','VL'],
['Dökme katı','VO'],
['Vakumlu','VP'],
['Dökme sıvılaştırılmış gaz','VQ'],
['Araç','VN'],
['Dökme katı granül','VR'],
['Dökme metal hurda','VS'],
['Dökme ince parçacıklar','VY'],
['Ortaboy dolum konteynerı','WA'],
['Hasırlı şişe','WB'],
['Ortaboy çelik dolum konteynerı','WC'],
['Ortaboy alüminyum dolum konteynerı','WD'],
['Ortaboy metal dolum konteynerı','WF'],
['Sıvılar için ortaboy çelik dolum konteynerı','WK'],
['Sıvılar için ortaboy alümünyum dolum konteynerı','WL'],
['Sıvılar için ortaboy metal dolum konteynerı','WM'],
['Ortaboy iç astarsız örme plastik dolum konteynerı','WN'],
['Ortaboy iç astarlı örme plastik dolum konteynerı','WR'],
['Ortaboy plastik film dolum konteynerı','WS'],
['Ortaboy iç astarsız kumaş plastik dolum konteynerı','WT'],
['Ortaboy iç astarlı doğal ahşap dolum konteynerı','WU'],
['Ortaboy iç astarlı kumaş dolum konteynerı','WX'],
['Ortaboy iç astarlı kontraplak dolum konteynerı','WY'],
['Ortaboy iç astarlı sunta dolum konteynerı','WZ'],
['İç astarsız örme plastik torba','XA'],
['Sızdırmaz örme plastik torba','XB'],
['Su geçirmez örme plastik torba','XC'],
['Plastik film torba','XD'],
['İç astarsız kumaş torba','XF'],
['Sızdırmaz kumaş torba','XG'],
['Su geçirmez kumaş torba','XH'],
['Çok duvarlı kağıt torba','XJ'],
['Su geçirmez çok duvarlı kağıt torba','XK'],
['Kompozit ambalaj, çelik bidon içindeki plastik kap','YA'],
['Kompozit ambalaj, çelik kasa içindeki plastik kap','YB'],
['Kompozit ambalaj, alüminyum bidon içindeki plastik kap','YC'],
['Kompozit ambalaj, alüminyum kasa içindeki plastik kap','YD'],
['Kompozit ambalaj, ahşap kutu içindeki plastik kap','YF'],
['Kompozit ambalaj, kontraplak bidon içindeki plastik kap','YG'],
['Kompozit ambalaj, kontraplak kasa içindeki plastik kap','YH'],
['Kompozit ambalaj, elyaf bidon içindeki plastik kap','YJ'],
['Kompozit ambalaj, elyaf levha kasa içindeki plastik kap','YK'],
['Kompozit ambalaj, plastik bidon içindeki plastik kap','YL'],
['Kompozit ambalaj, yekpare plastik kasa içindeki plastik kap','YM'],
['Kompozit ambalaj, çelik bidon içindeki cam kap','YN'],
['Kompozit ambalaj, elyaf levha kasa içindeki plastik kap','YP'],
['Kompozit ambalaj, alüminyum bidon içindeki cam kap','YQ'],
['Kompozit ambalaj, alüminyum kasa içindeki plastik kap','YR'],
['Kompozit ambalaj, ahşap kasa içindeki cam kap','YS'],
['Kompozit ambalaj, kontraplak bidon içindeki cam kap','YT'],
['Kompozit ambalaj, hasır sepet içindeki cam kap','YV'],
['Kompozit ambalaj, elyaf bidon içindeki cam kap','YW'],
['Kompozit ambalaj, elyaf levha kasa içindeki cam kap','YX'],
['Kompozit ambalaj, genişleyebilir plastik paket içindeki cam kap','YY'],
['Kompozit ambalaj, yekpare plastik paket içindeki cam kap','YZ'],
['Ortaboy çok duvarlı kağıt dolum konteynerı','ZA'],
['Büyük boy torba','ZB'],
['Ortaboy çok duvarlı su geçirmez kağıt dolum konteynerı','ZC'],
['Ortaboy kompozit yekpare sert plastik dolum konteynerı','ZL'],
['Ortaboy kompozit yekpare esnek plastik dolum konteynerı','ZM'],
['Ortaboy kompozit sıkıştırılmış sert plastik dolum konteynerı','ZN'],
['Ortaboy kompozit sıkıştırılmış esnek plastik dolum konteynerı','ZP'],
['Sıvılar için ortaboy kompozit sert plastik dolum konteynerı','ZQ'],
['Sıvılar için ortaboy kompozit esnek plastik dolum konteynerı','ZR'],
['Ortaboy kompozit dolum konteynerı','ZS'],
['Ortaboy elyaf levha dolum konteynerı','ZT'],
['Ortaboy esnek dolum konteynerı','ZU'],
['Ortaboy doğal ahşap dolum konteynerı','ZW'],
['Ortaboy kontraplak dolum konteynerı','ZX'],
['Ortaboy sunta dolum konteynerı','ZY']
];
	
	
//	0=Belirtilmedi,1=Denizyolu, 2=Demiryolu, 3=Karayolu, 4=Havayolu, 5=Posta, 6=Çok araçlı, 7=Sabit taşıma tesisleri, 8=İç su taşımacılığı
	var gonderilmeSekliListesi = [
		['Belirtilmedi','0'], ['Denizyolu','1'], ['Demiryolu','2'], ['Karayolu','3'], ['Havayolu','4'], ['Posta','5'],
		['Çok araçlı','6'], ['Sabit taşıma tesisleri','7'], ['İç su taşımacılığı','8']
	];
	
	var digerVergilerCmbListesi = [ 
   		["V0021","BANKA MUAMELELERİ VER."],['V0061','KKDF KESİNTİ'], ['V0071','ÖTV 1. LİSTE'],
   		['V0073','ÖTV 3. LİSTE'], ['V0074',	'ÖTV 4. LİSTE'], ['V0075',	'ÖTV 3A LİSTE'],
   		['V0076','ÖTV 3B LİSTE'], ['V0077',	'ÖTV 3C LİSTE'], ["V1047","DAMGA V"],["V1048","5035SKDAMGAV"],
   		["V4080","Ö.İLETİŞİM V"], ["V4081","5035ÖZİLETV."], ["V9015","KDV TEVKİFAT"],["V9021","4961BANKASMV"],
   		["V9077","ÖTV 2.LİSTE"], ["V8001","BORSA TES.ÜC."], ["V8002","ENERJİ FONU"], ["V4071","ELK.HAVAGAZ.TÜK.VER."],
   		["V8004","TRT PAYI"], ["V8005","ELK.TÜK.VER."], ["V8006","TK KULLANIM"], ["V8007","TK RUHSAT"],
   		["V8008","ÇEV. TEM .VER."],["V0003","GV. STOPAJI"],["V0011","KV. STOPAJI"],["V9040","MERA FONU"],
   		["V4171","ÖTV 1. LİSTE TEVKİFAT"],["V9944","BEL.ÖD.HAL RÜSUM"]
   		,["V0059","KONAKLAMA VERGİSİ"]
   	];


	var yolcuberaberAraciFirmaListesi = [
		['3810044287','Global Blue Turistik Hizmetler A.Ş.'],
		['9240492958','VERGİ İADE ARACILIK A.Ş. (Tax Free Zone)'],
		['6230448891','MR TURİSTİK ARACILIK VE DANIŞMANLIK HİZM. A.Ş.'],
		['4842128198','JOY REFUND VERGİ İADE ARACILIK HİZMETLERİ A.Ş.']
	];
	
	var iskontoArttirimListesi  = [
		['İskonto',	'ISKONTO'], ['Arttırım','ARTTIRIM']
	];
	
	var gumrukRejimKodlari = [
		['1000 - Daha önce bir rejime tabi tutulmamış eşyanın kesin ihracatı','1000'],
		['1021 - Hariçte işleme rejimi kapsamında geçici ihraç edilen eşyanın kesin ihracatı','1021'],
		['1023 - İhraç edildiği şekli ile geri gelmek üzere geçici ihraç edilen eşyanın kesin ihracatı','1023'],
		['1040 - Muafiyete tabi olmadan serbest dolaşım ile eş zamanlı yurtiçi kullanıma giren eşyanın kesin ihracatı','1040'],
		['1042 - Muafiyete tabi olarak serbest dolaşım ile eş zamanlı yurtiçi kullanıma giren eşyanın kesin ihracatı','1042'],
		['1072 - Antrepoya alınan serbest dolaşımda bulunan eşyanın kesin ihracatı','1072'],
		['1091 - Gümrük kontrolü altında işleme rejimine tabi tutulan eşyanın kesin ihracatı','1091'],
		['2100 - Serbest dolaşımda bulunan eşyanın hariçte işleme rejimi kapsamında geçici ihracatı','2100'],
		['2123 - İhraç edildiği şekli ile geri gelmek üzere geçici ihraç edilen eşyanın hariçte işleme rejimi kapsamında geçici ihracatı','2123'],
		['2141 - Dahilde işleme rejimi geri ödeme sistemi çerçevesinde serbest dolaşım ile eş zamanlı yurtiçi kullanıma giren eşyanın hariçte işleme rejimi kapsamında geçici ihracatı','2141'],
		['2151 - Dahilde işleme rejimi şartlı muafiyet sistemine tabi tutulan eşyanın hariçte işleme rejimi kapsamında geçici ihracatı ','2151'],
		['2152 - 51 no.lu kodda belirtilenin dışında dahilde işleme rejimine tabi eşyanın hariçte işleme rejimi kapsamında geçici ihracatı','2152'],
		['2153 - Geçici ithalat rejimi kapsamında ithal edilen eşyanın hariçte işleme rejimi kapsamında geçici ihracatı ','2153'],
		['2172 - Antrepoya alınan serbest dolaşımda bulunan eşyanın hariçte işleme rejimi kapsamında geçici ihracatı','2172'],
		['2191 - Gümrük kontrolü altında işleme rejimine tabi tutulan eşyanın hariçte işleme rejimi kapsamında geçici ihracatı','2191'],
		['2300 - Daha önce bir rejime tabi tutulmamış eşyanın ihraç edildiği şekli ile geri gelmek üzere geçici ihracatı','2300'],
		['2340 - Muafiyete tabi olmadan serbest dolaşım ile eş zamanlı yurtiçi kullanıma giren eşyanın ihraç edildiği şekli ile geri gelmek üzere geçici ihracatı','2340'],
		['2341 - Dahilde işleme rejimi geri ödeme sistemi çerçevesinde serbest dolaşım ile eş zamanlı yurtiçi kullanıma giren eşyanın ihraç edildiği şekli ile geri gelmek üzere geçici ihracatı','2341'],
		['2342 - Muafiyete tabi olarak serbest dolaşım ile eş zamanlı yurtiçi kullanıma giren eşyanın ihraç edildiği şekli ile geri gelmek üzere geçici ihracatı','2342'],
		['2351 - Dahilde işleme rejimi şartlı muafiyet sistemine tabi tutulan eşyanın ihraç edildiği şekli ile geri gelmek üzere geçici ihracatı','2351'],
		['2352 - 51 no.lu kodda belirtilenin dışında dahilde işleme rejimine tabi tutulan eşyanın ihraç edildiği şekli ile geri gelmek üzere geçici ihracatı','2352'],
		['2353 - Geçici ithalat rejimi kapsamında ithal edilen eşyanın ihraç edildiği şekli ile geri gelmek üzere geçici ihracatı','2353'],
		['2600 - ATA Karnesi kapsamında eşyanın geçici ihracatı ','2600'],
		['3141 - Dahilde işleme rejimi geri ödeme sistemi kapsamında serbest dolaşım ile eş zamanlı yurtiçi kullanıma giren eşyanın yeniden ihracatı','3141'],
		['3151 - Dahilde işleme rejimi şartlı muafiyet sistemine tabi tutulan eşyanın yeniden ihracatı','3151'],
		['3152 - 51 no.lu kodda belirtilenin dışında dahilde işleme rejimine tabi tutulan eşyanın yeniden ihracatı','3152'],
		['3153 - Geçici ithalat rejimi kapsamında ithal edilen eşyanın yeniden ihracatı','3153'],
		['3158 - ATA Karnesi kapsamında geçici ithal edilen eşyanın yeniden ihracatı ','3158'],
		['3171 - Gümrük idaresince eşya konulmasına izin verilen yerler dahil olmak üzere gümrük antrepo rejimine tabi tutulan serbest dolaşımda bulunmayan eşyanın yeniden ihracatı','3171'],
		['4000 - Daha önce bir rejime tabi tutulmamış eşyanın muafiyete tabi olmadan serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4000'],
		['4010 - İhraç edilen eşyanın muafiyete tabi olmadan serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4010'],
		['4051 - Dahilde işleme rejimi şartlı muafiyet sistemine tabi tutulan eşyanın muafiyete tabi olmadan serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4051'],
		['4053 - Geçici ithalat rejimi kapsamında ithal edilen eşyanın muafiyete tabi olmadan serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4053'],
		['4058 - ATA Karnesi kapsamında geçici ithal edilen eşyanın muafiyete tabi olmadan serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı ','4058'],
		['4071 - Gümrük idaresince eşya konulmasına izin verilen yerler dahil olmak üzere gümrük antrepo rejimine tabi tutulan serbest dolaşımda bulunmayan eşyanın  muafiyete tabi olmadan serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4071'],
		['4072 - Antrepo rejimine tabi tutulan serbest dolaşımdaki eşyanın Türkiye Gümrük Bölgesine girişi','4072'],
		['4091 - Gümrük kontrolü altında işleme rejimine tabi tutulan eşyanın muafiyete tabi olmadan serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4091'],
		['4100 - Daha önce bir rejime tabi tutulmamış eşyanın dahilde işleme rejimi geri ödeme sistemi kapsamında serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4100'],
		['4121 - Hariçte işleme rejimi kapsamında geçici ihraç edilen eşyanın dahilde işleme rejimi geri ödeme sistemi kapsamında serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4121'],
		['4123 - İhraç edildiği şekli ile geri gelmek üzere geçici ihraç edilen eşyanın dahilde işleme rejimi geri ödeme sistemi kapsamında serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı ','4123'],
		['4171 - Gümrük idaresince eşya konulmasına izin verilen yerler dahil olmak üzere gümrük antrepo rejimine tabi tutulan serbest dolaşımda bulunmayan eşyanın dahilde işleme rejimi geri ödeme sistemi kapsamında serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4171'],
		['4191 - Gümrük kontrolü altında işleme rejimine tabi tutulan eşyanın dahilde işleme rejimi geri ödeme sistemi kapsamında serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4191'],
		['4200 - Daha önce bir rejime tabi tutulmamış eşyanın muafiyete tabi olarak serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4200'],
		['4210 - İhraç edilen eşyanın muafiyete tabi olarak serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4210'],
		['4251 - Dahilde işleme rejimi şartlı muafiyet sistemine tabi tutulan eşyanın muafiyete tabi olarak serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4251'],
		['4253 - Geçici ithalat rejimi kapsamında ithal edilen eşyanın muafiyete tabi olarak serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4253'],
		['4258 - ATA Karnesi kapsamında geçici ithal edilen eşyanın muafiyete tabi olarak serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4258'],
		['4271 - Gümrük idaresince eşya konulmasına izin verilen yerler dahil olmak üzere gümrük antrepo rejimine tabi tutulan  serbest dolaşımda bulunmayan eşyanın muafiyete tabi olarak serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4271'],
		['4291 - Gümrük kontrolü altında işleme rejimine tabi tutulan eşyanın muafiyete tabi olarak serbest dolaşıma girişi ile eş zamanlı yurtiçi kullanımı','4291'],
		['5100 - Daha önce bir rejime tabi tutulmamış eşyanın dahilde işleme rejimi şartlı muafiyet sistemine tabi tutulması','5100'],
		['5121 - Hariçte işleme rejimi kapsamında geçici ihraç edilen eşyanın dahilde işleme rejimi şartlı muafiyet sistemine tabi tutulması ','5121'],
		['5123 - İhraç edildiği şekli ile geri gelmek üzere geçici ihraç edilen eşyanın dahilde işleme rejimi şartlı muafiyet sistemine tabi tutulması ','5123'],
		['5141 - Dahilde işleme rejimi geri ödeme sistemi kapsamında serbest dolaşım ile eş zamanlı yurtiçi kullanıma giren eşyanın dahilde işleme rejimi şartlı muafiyet sistemine tabi tutulması','5141'],
		['5171 - Gümrük idaresince eşya konulmasına izin verilen yerler dahil olmak üzere gümrük antrepo rejimine tabi tutulan serbest dolaşımda bulunmayan eşyanın dahilde işleme rejimi şartlı muafiyet sistemine tabi tutulması','5171'],
		['5191 - Gümrük kontrolü altında işleme rejimine tabi tutulan eşyanın dahilde işleme rejimi şartlı muafiyet sistemine tabi tutulması ','5191'],
		['5200 - Daha önce bir rejime tabi tutulmamış eşyanın 51 no.lu kodda belirtilenin dışında dahilde işleme rejimine tabi tutulması','5200'],
		['5221 - Hariçte işleme rejimi kapsamında geçici ihraç edilen eşyanın 51 no.lu kodda belirtilenin dışında dahilde işleme rejimine tabi tutulması','5221'],
		['5223 - İhraç edildiği şekli ile geri gelmek üzere geçici ihraç edilen eşyanın 51 no.lu kodda belirtilenin dışında dahilde işleme rejimine tabi tutulması ','5223'],
		['5271 - Gümrük kontrolü altındaki yerler dahil olmak üzere gümrük antrepo rejimine tabi tutulan serbest dolaşımda bulunmayan eşyanın 51 no.lu kodda belirtilenin dışında dahilde işleme rejimine tabi tutulması','5271'],
		['5291 - Gümrük kontrolü altında işleme rejimine tabi tutulan eşyanın 51 no.lu kodda belirtilenin dışında dahilde işleme rejimine tabi tutulması','5291'],
		['5300 - Daha önce bir rejime tabi tutulmamış eşyanın geçici ithalat rejimi kapsamında ithalatı','5300'],
		['5321 - Hariçte işleme rejimi kapsamında geçici ihraç edilen eşyanın geçici ithalat rejimi kapsamında ithalatı','5321'],
		['5323 - İhraç edildiği şekli ile geri gelmek üzere geçici ihraç edilen eşyanın geçici ithalat rejimi kapsamında ithalatı','5323'],
		['5341 - Dahilde işleme rejimi geri ödeme sistemi kapsamında serbest dolaşım ile eş zamanlı yurtiçi kullanıma giren eşyanın geçici ithalat rejimi kapsamında ithalatı','5341'],
		['5351 - Dahilde işleme rejimi şartlı muafiyet rejimine tabi tutulan eşyanın geçici ithalat rejimi kapsamında ithalatı','5351'],
		['5352 - 51 no.lu kodda belirtilenin dışında dahilde işleme rejimine tabi tutulan eşyanın geçici ithalat rejimi kapsamında ithalatı','5352'],
		['5353 - Geçici ithalat rejimine tabi tutulan eşyanın devrini müteakiben geçici ithalat rejimine tabi tutulması','5353'],
		['5358 - ATA Karnesi kapsamında geçici ithalatı yapılan eşyanın devrini müteakiben geçici ithalat rejimine tabi tutulması','5358'],
		['5371 - Gümrük idaresince eşya konulmasına izin verilen yerler dahil olmak üzere gümrük antrepo rejimine tabi tutulan serbest dolaşımda bulunmayan eşyanın geçici ithalat rejimi kapsamında ithalatı','5371'],
		['5391 - Gümrük kontrolü altında işleme rejimine tabi tutulan eşyanın geçici ithalat rejimi kapsamında ithalatı','5391'],
		['5800 - ATA Karnesi kapsamında geçici ithalat ','5800'],
		['6121 - Hariçte işleme rejimi kapsamında geçici ihraç edilen eşyanın vergi muafiyeti uygulanmaksızın yeniden ithalatı','6121'],
		['6123 - İhraç edildiği şekli ile geri gelmek üzere geçici ihraç edilen eşyanın vergi muafiyeti uygulanmaksızın yeniden ithalatı ','6123'],
		['6321 - Hariçte işleme rejimi kapsamında geçici ihraç edilen eşyanın vergi muafiyeti ile serbest dolaşım ve yurtiçi kullanıma eş zamanlı girerek yeniden ithalatı','6321'],
		['6323 - İhraç edildiği şekli ile geri gelmek üzere geçici ihraç edilen eşyanın vergi muafiyeti ile serbest dolaşım ve yurtiçi kullanıma eş zamanlı girerek yeniden ithalatı','6323'],
		['6326 - ATA Karnesi kapsamında geçici ihraç edilen eşyanın yeniden ithalatı ','6326'],
		['6521 - Hariçte işleme rejimi kapsamında geçici ihraç edilen eşyanın 51 no.lu kodda belirtilenin dışında dahilde işleme rejimi ve serbest dolaşıma eş zamanlı giren eşyanın yeniden ithalatı ','6521'],
		['6523 - İhraç edildiği şekli ile geri gelmek üzere ihraç edilen eşyanın 51 no.lu kodda belirtilenin dışında dahilde işleme rejimi ve serbest dolaşıma eş zamanlı giren eşyanın yeniden ithalatı','6523'],
		['6771 - Geçici ihraç edildikten sonra yurda dönen ve antrepo rejimine tabi tutulan eşyanın yeniden ithalatı','6771'],
		['7100 - Daha önce bir rejime tabi tutulmamış eşyanın gümrük idaresince eşya konulmasına izin verilen yerler dahil olmak üzere gümrük antrepo rejimine tabi tutulması ','7100'],
		['7121 - Hariçte işleme rejimi kapsamında geçici ihraç edilen eşyanın gümrük idaresince eşya konulmasına izin verilen yerler dahil olmak üzere gümrük antrepo rejimine tabi tutulması ','7121'],
		['7123 - İhraç edildiği şekli ile geri gelmek üzere ihraç edilen eşyanın gümrük idaresince eşya konulmasına izin verilen yerler dahil olmak üzere gümrük antrepo rejimine tabi tutulması','7123'],
		['7141 - Dahilde işleme rejimi geri ödeme sistemi kapsamında serbest dolaşım ile eş zamanlı yurtiçi kullanıma giren eşyanın gümrük idaresince eşya konulmasına izin verilen yerler dahil olmak üzere gümrük antrepo rejimine tabi tutulması','7141'],
		['7151 - Dahilde işleme rejimi şartlı muafiyet sistemine tabi tutulan eşyanın gümrük idaresince eşya konulmasına izin verilen yerler dahil olmak üzere gümrük antrepo rejimine tabi tutulması','7151'],
		['7153 - Geçici ithalat rejimi kapsamında ithal edilen eşyanın gümrük idaresince eşya konulmasına izin verilen yerler dahil olmak üzere gümrük antrepo rejimine tabi tutulması','7153'],
		['7158 - ATA Karnesi kapsamında geçici ithal edilen eşyanın antrepo rejimine tabi tutulması ','7158'],
		['7171 - Gümrük idaresince eşya konulmasına izin verilen yerler dahil olmak üzere gümrük antrepo rejimine tabi tutulan eşyanın; aynı gümrük idaresi denetimindeki başka bir yer veya antrepoya konulması ya da aynı antrepoda başkasına satış suretiyle devredilmesi','7171'],
		['7191 - Gümrük kontrolü altında işleme rejimine tabi tutulan eşyanın gümrük idaresince eşya konulmasına izin verilen yerler dahil olmak üzere gümrük antrepo rejimine tabi tutulması','7191'],
		['7200 - Serbest dolaşımda bulunan eşyanın antrepoya konulması','7200'],
		['7241 - Dahilde işleme rejimi geri ödeme sistemi kapsamında serbest dolaşım ile eş zamanlı yurtiçi kullanıma giren serbest dolaşımda bulunan eşyanın antrepoya konulması','7241'],
		['7252 - 51 no.lu kodda belirtilenin dışında dahilde işleme rejimine tabi tutulan serbest dolaşımda bulunan eşyanın antrepoya konulması','7252'],
		['7272 - Antrepoya konulan serbest dolaşımda bulunan eşyanın aynı gümrük idaresinin denetimindeki başka bir antrepoya konulması','7272'],
		['9100 - Daha önce bir rejime tabi tutulmamış eşyanın gümrük kontrolü altında işleme rejimine tabi tutulması ','9100'],
		['9171 - Gümrük idaresince eşya konulmasına izin verilen yerler dahil olmak üzere gümrük antrepo rejimine tabi tutulan eşyanın gümrük kontrolü altında işleme rejimine tabi tutulması','9171']
	];
	

/** ******************************* */
/** *******ORTAK METODLAR********** */
/** ******************************* */

/**
 * dizinin icini bosaltir
 */
function clearArray (array) {
	for (var i = 0, len = array.length; i < len; i++){
		array.splice(0, 1);
	}   		
}	

function rendererEvetHayir (value) {
	if (value == true)
    	return "Evet";
    else
    	return "Hay\u0131r";
}

/**
 * @param date
 *            (Date tipinde gelmelidir, Extjs sınıfı), dd/mm/yyyy seklindeki
 *            string'i yyyymmdd sekline cevirir<br>
 *            null ise "" doner
 */
function formatDate (date) {
	if (date && date instanceof Date) {
		return date.format('Ymd');
	}
	return "";
}

function rendererLongDate (date) {
	if (date && "" != date) {
		var dt = Date.parseDate(date, "Ymdhis" );
		return dt.format('d/m/Y H:i:s');
	}
	return "";
}

/**
 * turk para birimine cevirir
 */
function rendererTRYCurrency (cur) {
	if (cur && "" != cur) {
		var str =  new String(cur);
		return str.replace('.',",") + " TRY";
	}
	return "";
}

Ext.override(Ext.form.Field, {
	setFieldLabel : function(text) {
		if (this.rendered) {
			this.el.up('.x-form-item', 10, true).child('.x-form-item-label').update(text);
		} else {
			this.fieldLabel = text;
		}
	}
	
});